### ISSUE TITLE
Document new typeclasses and semantics

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1050]
I think we should effectively redo all of the abstraction documentation. Each class should be documented individually, with examples and rationale for why it is the way it is, and a discussion of semantics and use-cases.

**Comment by RaasAhsan** [comment]
Do you think this belongs in the Scaladoc or in the mdoc, or both? I feel like the Scaladoc is the right place for the "definitive" documentation because it co-exists with the typeclass definition so it's easier to keep up to date. Maybe the mdoc can be focused on covering details, common usage, examples and so on like you had for what you started.

**Comment by TimWSpence** [comment]
If we have a concensus on what we want to achieve with these docs then I can have a go at them. I think a principle that was previously thrown around but never formalized was that high-level understanding and motivation belonged in mdoc and scaladoc would (and usually already does) have the gnarly details. Which I _think_ roughly aligns with what you've both said?

**Comment by kubukoz** [comment]
Can we sync the scaladoc with the website? 🤔

**Comment by TimWSpence** [comment]
I've started this work [here](https://github.com/TimWSpence/cats-effect/tree/split-typeclass-docs) for those who want to follow along

**Comment by djspiewak** [comment]
I believe this can now be closed. Amazing work, @TimWSpence!
