### ISSUE TITLE
Exception silently ignored in async after callback

### ISSUE THREAD

**Issue by durban** [typelevel/cats-effect#108]
I'm not sure if this is a bug, but it's surprising:
```scala
scala> val tsk = cats.effect.IO.async[Int] { cb => cb(Right(42)); throw new Exception }
tsk: cats.effect.IO[Int] = IO$830563880

scala> tsk.unsafeRunSync()
res1: Int = 42
```
It's probably due to [this line](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/IO.scala#L427): the callback would be called twice in this case, but the second one (with the exception) is ignored (correctly) due to the `onceOnly`.

**Comment by johnynek** [comment]
this has to be a bug. Silently swallowing exceptions it not okay.

**Comment by pchlupacek** [comment]
I am not sure. 
 - function to async must be pure
 - the exception is thrown **AFTER** the `cb` was invoked. In fact I think the incorrect is the second invocation of the `cb` with failure (if thats the case), which luckily get caught over the `onceOnly` guard. Rather, I think its so incorrect that perhaps failing the thread or doing something disastrous (like stdErr println, system.exit) shall be the correct approach here.

**Comment by pchlupacek** [comment]
to be precise function must not be pure, but shall not throw any `uncontrolled` exceptions.

**Comment by johnynek** [comment]
I am just imagining terrible errors like thread interrupted, linkage errors, classnotfound, etc....

I don't want those swallowed no matter what people think about exceptions. I don't throw exceptions, but we are on the JVM, we can't wish them away.

**Comment by pchlupacek** [comment]
Note the exception thrown **after** `cb` is invoked. I cannot imagine there is sound scenario for that.

**Comment by djspiewak** [comment]
@johnynek @durban It's not a bug; it's by design.  What else would you expect it to do?  I can `printStackTrace()`, but that's about it.  You can see why this is forced by looking at the type signature (which doesn't take any parameters other than the function) and running the following test:

```scala
val tu: IO[Unit] = IO async { cb =>
  cb(Right(()))
  println("about to explode!")
  throw new RuntimeException
}

val program = tu *> IO(println("continuing"))
program.unsafeRunSync()
```

This will print the following:

```
continuing
about to explode!
```

So the exception is actually happening *after* the rest of your program, though we can't know that for sure.

**Comment by johnynek** [comment]
A related issue comes up for instance in twitter util's Future where there are functions that when they throw don't make sense to change the result of some Future. Monitor is used to at least be able to log, count, etc... such failures so you don't have the possibility of totally silently swallowing exceptions:

https://twitter.github.io/util/docs/com/twitter/util/Monitor$.html

I haven't looked in detail at your implementation, but without this it makes `IO.async` a potential source of very hard to debug issues if there is not some way to observe an exception being thrown after the function has been called.

**Comment by djspiewak** [comment]
I mean, you shouldn't be doing things that could conceivably throw after a callback invocation inside of async.  Also if you're invoking the callback synchronously, you probably shouldn't use `async` at all, and an async invocation wouldn't have this issue since the exception would probably happen *first*.  For all of these reasons, I honestly don't feel like this is a particularly serious issue: it's just never going to come up.

If we did want to fix it though…  We could take an `implicit` `ExecutionContext`, which would give us the ability to report the errors.  I'm not fond of that though, since the type effectively lies by implying that it's doing something with thread shifting, when really the only thing we care about is the error reporting.

**Comment by johnynek** [comment]
Anything can potententially throw a ClassNotFound exception including just using static code. Similarly with NoClassDefFound. Sadly, in very large codebases with occasional runtime classpath issues, these happen. Silently burying that exception would be very bad in that case (it would be quite confusing why things weren't working).

I am biased in that I work in very large codebases and with less experienced scala folks. I can tell you, these things come up. I hope we don't optimize for the small code-base/expert-only end of the spectrum since that prevents me from being able to use the library due to unfairly burdening my coworkers with overly difficult to debug corner cases.

**Comment by johnynek** [comment]
PS: we have seen the ClassNotFound bug twice in the past week due to a cache error on our CI, but it is not uncommon at all on hadoop/spark/storm situations.

**Comment by durban** [comment]
Yes, of course, that `IO` cannot be failed, since it's already succeeded when the exception occurred (I'm sorry I didn't specify this originally). I also agree, that this probably rarely happens in practice. (Although when it does happen, it will be confusing due to the silently swallowed exception.)

I also don't have a better idea than `printStackTrace`. (I also looked at `UncaughtExceptionHandler`, but that seems to be for when the thread dies.)

**Comment by alexandru** [comment]
In Monix the `Task` implementation depends on having a `Scheduler` for execution which gets injected everywhere, inheriting from `ExecutionContext`, which has a [reportFailure](https://www.scala-lang.org/api/current/scala/concurrent/ExecutionContext.html#reportFailure(cause:Throwable):Unit) utility on it, such that unexpected errors in `Task.create` can get reported.

By default the `global` scheduler / ec will report on $stderr, however you can configure your own `ExecutionContext` or your own `Scheduler` with Monix that redirects those errors to Logback or whatever.

That said, the guarantees you get in Monix's `Task.create` about what error gets reported by means of that callback are even weaker than in `cats-effect` because Monix does not do any synchronization to guard against repeated calls of that callback. So `Task.create` looks like this:

```scala
try {
  val ref = register(s, new CreateCallback(conn, cb)(s))
  cancelable := ref
} catch {
  case NonFatal(ex) =>
    // We cannot stream the error, because the callback might have
    // been called already and we'd be violating its contract,
    // hence the only thing possible is to log the error.
    s.reportFailure(ex)
}
```

In other words, an exception gets caught from that `register` function? We assume that the callback was already called, even if we don't have any evidence for it and attempting to call it again would result in a *protocol violation*.

So here's the issue — exceptions being thrown in `IO.async` or `Task.create` are a **protocol violation**. And when speaking of an asynchronous producer-consumer protocol of communication, such as what we have here, the two parties must respect that protocol otherwise there often isn't any sensible fallback mechanism.

For a more complicated protocol I encourage you to take a look at [Reactive Streams](http://www.reactive-streams.org/), which is describing streaming with back-pressure and that Monix also implements. A lot of the details therein are hidden from the user of course, but then if the user plays with `Observable.unsafeCreate` which exposes Monix's `Future`-based back-pressure protocol, the user is expected to learn that protocol and to apply it wisely, otherwise there are instances in which the communication will be broken without the implementation being able to do anything about it.

As a funny fact, I often get bug reports about `Observable.flatMap` throwing concurrency errors — `flatMap` has a protection in place that I added because I was unsure about the implementation is correct and it turned out that the protection in question blows in people's faces whenever they violate the communication protocol. The solution in this particular case, for users not knowing what they are doing, is to use the safe `Observable.create` which exposes a buffered subscriber, but then you're working with a buffer and no longer have the ability to control the back-pressure.

---

It's not correct to do a `printStackTrace` because many web services will just throw that into `/dev/null`, relying on logging libraries like Logback to report any errors that happen.

And because `cats.effect.IO` does not have an underlying `Scheduler` or `ExecutionContext` that can report errors in such instances, the only sensible thing to do is to re-throw the error.

Re-throwing the error will either blow the main application thread, or the thread of a thread-pool that has exception reporting in place. With a sane thread-pool implementation and configuration (N.B. not all of them are sane), you can then get error reporting for unhandled errors.

**Comment by alexandru** [comment]
Please review my PR #111 and let me know if my proposal is 👍 or 👎

**Comment by alexandru** [comment]
Ping — can I get feedback on #111? Is this something we want?
