### ISSUE TITLE
Determine the fate of MVar

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1115]
There's been a lot of discussion about what we should do about `MVar`. It's a fun type to demo and play around with but it's almost never useful in practice and its performance is lackluster, which makes it a poor concurrency primitive to build more advanced data structures like queues. It's also pretty hard to test (we have some non-deterministic tests for it).

Related to #1017 , which proposes capturing mutable state in the `kernel`, but doesn't include `MVar`. We could either leave it in `concurrent` or just delete it, but that would surely surprise users who do happen to use it when they migrate.

**Comment by djspiewak** [comment]
Kill it with fire.

IMO

**Comment by Avasil** [comment]
I sometimes use it as a specialized asynchronous queue of size 1 but I can always use a queue instead so I don't mind removing it.

**Comment by djspiewak** [comment]
It has been decided. Its doom has been sealed.

**Comment by CremboC** [comment]
I personally find MVar very useful as a "transient cached promise", here's the exact code I got:
```scala
import cats.effect.Async
import cats.effect.concurrent.{MVar, Ref}
import cats.syntax.all._

sealed trait Promise[F[_], A] {
  def await: F[A]
}

sealed trait CompletablePromise[F[_], A] extends Promise[F, A] {
  def complete(a: A): F[Boolean]
}

object Promise {
  final def transientlyCached[F[_]: Async, A](maxAccesses: Int): F[CompletablePromise[F, A]] =
    for {
      ref  <- Ref.of(maxAccesses)
      mvar <- MVar.uncancelableEmpty[F, A]
    } yield new CompletablePromise[F, A] {
      final override val await: F[A] =
        for {
          v <- mvar.read
          i <- ref.updateAndGet(_ - 1)
          _ <- mvar.take.whenA(i == 0) // empty the MVar once we're done
        } yield v

      final override def complete(a: A): F[Boolean] = mvar.tryPut(a)

    }

  final def transient[F[_]: Async, A]: F[CompletablePromise[F, A]] =
    MVar.uncancelableEmpty[F, A].map { mvar =>
      new CompletablePromise[F, A] {
        final override val await: F[A]                = mvar.take
        final override def complete(a: A): F[Boolean] = mvar.tryPut(a)
      }
    }
}

```

The reason why I use this over `Deferred` is (in my understanding) if I empty an MVar, it basically allows the JVM to garbage collect the object that was in this temporary cache. If I used an MVar, it will basically remain there until I lose reference to the `Deferred`.

The more precise use case is basically I got a tree-like structure with 'holes' to fill - values that will be inserted via side effect. This can be a massive structure with literally 10s if not 100s of thousands of values to fill, occupying GBs of memory. 

Example tree: (sorry for terrible diagram)

```
                                            
                  Intersect                  
                   /----\                   
               /---      -----\             
             --                ---          
         Union                  Union       
         /-|\                   / | \       
      /--  / \                 |  |  -\     
   /--    |   \                /  |    \    
 --       |    -              |   |     -   
 V1      V2    V3             V1   V2   V4  
```

Ideally, once all branches of a subtree are resolved, I can merge them via the operator - `UNION(V1, V2, V3)` - and throw away the original values. However, you can see that V1 and V2 are re-used on the other subtree, so instead of fetching the value twice, I use an MVar with limited number of accesses to keep the value for a limited amount of time.

Maybe I'm using MVar really wrong and this is really stupid, but it's definitely useful for this particular use case!

**Comment by djspiewak** [comment]
The use case where you want a `Deferred` which ultimately goes back to being empty is definitely one that `MVar` handles better than the alternatives. You could potentially encode this with `Ref` and `Deferred` by having a `Ref[F, Option[Deferred[F, A]]]`. `take` then is equivalent to setting the `Ref` to `None`. Whenever you `read`, you have to `map(pure(_)).getOrElse(never)` to account for the fact that it might have been emptied.

I'm actually curious about this use case more generally. Why a fixed number of accesses? What's the broader context here?

**Comment by CremboC** [comment]
Your suggestion for using `Ref[F, Option[Deferred[F, A]]]` make sense. But, just to make sure, we still need to have a (semantically) blocking `read` call - i.e. if the value is not there, we should block until it's there. Also the semantics of 'tryPut' is important - but that's definitely easy to replicate with your suggestion.

> I'm actually curious about this use case more generally. Why a fixed number of accesses? What's the broader context here?

So as I showed in the example, we know exactly how many times the a given value will be used. Because of the potential memory use, we want allow values to be GC'd as soon as possible. A fixed number of access is basically like a reference counter.

Let me know if you want/need more detail.

EDIT:
I forgot to mention, I actually had this tested with both MVar and just a normal Deferred that doesn't empty the value and it would basically always OOM with big datasets unless I used MVar. So my theory of the JVM being able to GC the value checks out, I believe.

**Comment by SystemFw** [comment]
don't you need to reset `accesses` as well?

**Comment by CremboC** [comment]
@SystemFw hmm not sure what you mean - once the value has been accessed `n` times there no way it will be accessed again - we know that from the get-go before evaluating this tree.

**Comment by SystemFw** [comment]
Or is it like, once maxAccesses has happened we never want to `tryPut` or `get` again??

EDIT: maybe it is

**Comment by CremboC** [comment]
Yeah exactly - so `tryPut` should only be called once for a `Promise` - but due to quirks of the system (not important for this discussion) it may be called more than once. We actually return capture that as a metric because it's an indicator that something elsewhere is not quite right.

And `get` is 100% guaranteed to be only called `maxAccesses` amount of times. Once again, if it's not then we got a bug elsewhere.

**Comment by SystemFw** [comment]
```scala
 sealed trait Promise[F[_], A] {
    def await: F[A]
  }
  sealed trait CompletablePromise[F[_], A] extends Promise[F, A] {
    def complete(a: A): F[Boolean]
  }

  object Promise {
    def transientlyCached[F[_]: Concurrent, A](
        maxAccesses: Int
    ): F[CompletablePromise[F, A]] = {
      def empty = Deferred[F, A].map(d => (d, maxAccesses).some)

      empty
        .flatMap(v => Ref[F].of(v))
        .map { state =>
          new CompletablePromise[F, A] {
            def await: F[A] =
              state.modify {
                case Some((d, accesses)) if accesses == 1 =>
                  None -> d.get
                case Some((d, accesses)) =>
                  Some((d, accesses - 1)) -> d.get
                case None =>
                  throw new Exception("impossible")
              }.flatten

            def complete(a: A): F[Boolean] =
              state.get.flatMap {
                case None => false.pure[F]
                case Some((d, _)) =>
                  d.complete(a) // in ce3 it returns a boolean
                    .attempt
                    .map(_.isRight)
              }
          }
        }
    }

    def transient[F[_]: Concurrent, A]: F[CompletablePromise[F, A]] =
      Deferred[F, A].map { d =>
        new CompletablePromise[F, A] {
          val await: F[A] = d.get
          def complete(a: A): F[Boolean] =
            d.complete(a) // in ce3 it returns a boolean
              .attempt
              .map(_.isRight)
        }
      }
  }
```
something like this? (untested)

EDIT: also this version is much easier to make interruption safe by reincrementing `accesses`, if you need to

**Comment by CremboC** [comment]
@SystemFw not sure that's quite right.

The contract is basically:
- `await` should semantically block until value is available
- `await` should keep track of how many the value has been read
- `await` should release the value once the value has been read `maxAccesses` times (to allow for GC)
- `complete` should fill the value if it's empty and return `true` if it succeeded doing it. If the value is already present, do nothing and return `false`.

For the other impl (i.e. `def transient`) it should just empty value after it was read once (the exact semantics of `MVar`).

**Comment by SystemFw** [comment]
> await should semantically block until value is available

it does, it blocks on `d.get`

> await should keep track of how many the value has been read

it does, by decreasing `accesses` on each call

> await should release the value once the value has been read maxAccesses times (to allow for GC)

it does by setting the state to `None` if the access counter is at 1 once `await` is called (which means this call is the last one)

> complete should fill the value if it's empty and return true if it succeeded doing it. If the value is already present, do nothing and return false.

it does, although I've written it in ce2 where you need some mucking around. In ce3 it returns a boolean (with that behaviour) by default

**Comment by CremboC** [comment]
Ahh sorry, that's my inability to read `state.modify`. Fair enough, that looks reasonable. I guess `def transient` would become a specialised version of `def transientlyCached` with `maxAccess = 1`.

**Comment by SystemFw** [comment]
yeah I didn't take care of the clearing out there, but you can implement it with `maxAccess = 1`

**Comment by SystemFw** [comment]
I don't disagree that MVar is fine for your case btw, but the complexity of the strategy I've used (finite state machine with Ref + Deferred) scales very well with the complexity of the problem, whereas MVar devolves into almost guaranteed deadlock as your problem gets harder

**Comment by CremboC** [comment]
Assuming that works correctly and has the same (or better) memory/perf characteristics I'm perfectly happy to get rid of `MVar` haha. Thanks!

**Comment by SystemFw** [comment]
test it :P

**Comment by kubukoz** [comment]
Some users are going to be hit by this when migrating - what should we tell them? "Use queue(1)" isn't going to cut it if someone's currently using `modify` and other methods from `MVar2` (I know of one such example at $JOB already).

**Comment by djspiewak** [comment]
The answer really is "use Ref and Deferred". In most cases, the domain will break down nicely and the code will honestly be cleaner and easier to maintain. In rarer cases, you'll need a Ref *of* a Deferred and it will be slightly more involved, but still about the same as an MVar (just more explicit).

**Comment by kubukoz** [comment]
Can't say that's the best migration UX ;)

There should probably be at least a library one can use for the transition period, while they're busy figuring out changes related to new signatures, the disappearances of ExitCase, etc. (without having to come up with exhaustive test cases and whatnot) - someone will probably make one, let's hope 😅

**Comment by djspiewak** [comment]
I mean, I'm definitely not averse to a micro library which provides the functionality. Putting it into CE itself though would mean we're stuck with it forever.

**Comment by alexandru** [comment]
Just a note ... `MVar` is cool nonetheless and will continue to be exposed in the `monix-catnap` sub-project.

`monix-catnap` is the Monix sub-project with Cats-Effect related utilities.

**Comment by kubukoz** [comment]
@alexandru I noticed this today, `modify` seems to be missing from monix-catnap. If it were to be added, that'd be binary breaking (new abstract method, I think), so it's probably a good idea to add it when the CE3.0 breakage happens (if ever)?
