### ISSUE TITLE
Add Ref#modifyF

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1116]
It has a relatively obvious definition, we just need to carefully document the fact that it would rerun the effect.

**Comment by SystemFw** [comment]
I am unsure about this :)
Comments and all, it's still a footgun answer to a _very_ common question. If anything, we could/should add a more explicit combinator for the `modify().flatten` with `S => (S, F[A])` pattern

**Comment by djspiewak** [comment]
> Comments and all, it's still a footgun answer to a very common question

I mean, it is a footgun in a sense, but… maybe my perspective is skewed on this, but `modifyF`'s semantics are *exactly* what I expect *and want* looking at it from the outside. I *want* the effect to reevaluate on each loop of the CAS. It's what the type says, it's what I'm looking for. But maybe that's just a weird perspective?

Part of what I come back to on this is the fs2 `PubSub` issue. Without `modifyF`, you *have* to use an `unsafeRunSync()` to initialize `Ref` and `Deferred`. Fs2 can't be the only place where people are hitting that. And, here again we have a really good example of a situation where we *want* the effect to reevaluate on each CAS loop.

If people want to avoid reevaluation, `memoize` is going to be there; doesn't that solve the footgun concern?

**Comment by SystemFw** [comment]
> but modifyF's semantics are exactly what I expect and want looking at it from the outside. I want the effect to reevaluate on each loop of the CAS.

I think that's an uncommon experience :) When explaining/teaching this, most people don't even know what CAS is, and they assume locking semantics (like `withPermit` in Semaphore). And I think putting this op on our most prominent concurrent abstraction, especially with the obvious name, will cause a lot of people to mistakenly use it instead of `withPermit`.

> Without modifyF, you have to use an unsafeRunSync() to initialize Ref and Deferred. Fs2 can't be the only place where people are hitting that. And, here again we have a really good example of a situation where we want the effect to reevaluate on each CAS loop.

The easy solution is to just preallocate it though, which doesn't require unsafe ops, and imho is not that big of a deal in terms of perf cost. The other idea would be to just provide a custom method for this overwhelmingly common use case, something like `modifyAndWait(f: (S, Deferred[F, A]) => (S, F[A])): F[A]`, rather than exposing the whole thing.

> And, here again we have a really good example of a situation where we want the effect to reevaluate on each CAS loop

My view is basically that ~all the people that are capable of making that decision are also capable of implementing it themselves.

> If people want to avoid reevaluation, memoize is going to be there; doesn't that solve the footgun concern

I'm not so sure, because when people reach out for that type (based on anecdotical data on gitter), they are looking at a problem that either genuinely requires locking in their current design with `Ref` only (because the effect to produce depends on a state, you can't just produce it in advance with `memoize`), or requires a complete redesign in terms of `Ref/Deferred`.
