### ISSUE TITLE
IO.race cancelation issue

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats-effect#1132]
```scala
def time[A](ioa: IO[A]): IO[FiniteDuration] = 
  IO(System.nanoTime).flatMap { started => ioa >> IO((System.nanoTime - started).nanos) }

scala> time(IO.race(IO.unit, IO.race(IO.never, IO.sleep(10.seconds)))).unsafeRunSync
val res2: concurrent.duration.FiniteDuration = 10005052920 nanoseconds
```

**Comment by RaasAhsan** [comment]
I'm pretty sure this is because of https://github.com/typelevel/cats-effect/issues/1027. If you look at the definition of `race`, which is implemented in terms of `racePair`, that call is inside an `uncancelable` region, but not `poll`ed, because it's leaky right now, though Daniel posted a detailed analysis of why we should be safe in our current call sites of it. So the effect is that when the left-hand side of the outer `race` completes, it tries to `cancel` the right-hand side, which remains uncancelable for as long as it's masked.

**Comment by djspiewak** [comment]
@RaasAhsan Didn't we override that in `IO` though? I can't remember if that's just chilling on a local branch.

**Comment by RaasAhsan** [comment]
Looks like not https://github.com/typelevel/cats-effect/blob/series/3.x/core/shared/src/main/scala/cats/effect/IO.scala#L156

**Comment by mpilquist** [comment]
This is still a bug with current 3.0.0-M1

**Comment by RaasAhsan** [comment]
We just need to stick a `poll` around the `racePair` in the current definition, but I think this might solve it as well https://github.com/typelevel/cats-effect/pull/1157 ? Not sure, need to take a closer look

**Comment by djspiewak** [comment]
I believe this is now fixed. The following test passes:

```scala
        "immediately cancel inner race when outer unit" in real {
          for {
            start <- IO.monotonic
            _ <- IO.race(IO.unit, IO.race(IO.never, IO.sleep(10.seconds)))
            end <- IO.monotonic

            result <- IO((end - start) must beLessThan(5.seconds))
          } yield result
        }
```
