### ISSUE TITLE
Documentation site finishing touches

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1142]
- [ ] Review the `docs` branch
- [ ] Review https://github.com/typelevel/cats-effect/pull/1140
- [ ] Figure out what to put on the landing page (I can help adding it to the site)
- [x] Choose a code style template from https://highlightjs.org/static/demo/
- [x] Do we need a `clean` workflow?
- [ ] Release pipeline needs to kick off a job to update the submodule commit in the `docs` branch at `versions/2.x`

Also note that the current pipeline is pushing the generated site to `test-gh-pages`. You can download the contents of that branch, place it in a folder named `cats-effect`, then running `python -m SimpleHTTPServer` in the directory that contains `cats-effect`, and navigating to `http://localhost:8000`.

**Comment by djspiewak** [comment]
Regarding code style:

- I use Ocean in my editor, but we're not using a dark theme so I don't think it works as well
- I vote for GitHub Gist since it's basically "the color scheme of development pages"

> Do we need a clean workflow?

Nope. The existing one will murder artifacts across all branches.

> Release pipeline needs to kick off a job to update the submodule commit in the docs branch at versions/2.x

We'll also need a bot account to achieve this. I think Typelevel has one; I'll try to find out.

> Figure out what to put on the landing page (I can help adding it to the site)

On it!

**Comment by RaasAhsan** [comment]
In the `docs` branch you had `github gist` as the theme but it needs a dash. But I ended up switching to `github` since it has a more colorful palette and had a background color. Feel free to change it back to `github-gist` if you don't think so :P
