### ISSUE TITLE
Sync.mapSuspendsEvaluation cannot hold for Streams?

### ISSUE THREAD

**Issue by oleg-py** [typelevel/cats-effect#118]
I was trying to implement `Sync` instance for monix `Iterant` and noticed that it fails two laws:
* Sync.mapSuspendsEvaluation
* Sync.bindSuspendsEvaluation

I debugged the issue and it seems that everything breaks due to side-effecting function `evolve` being called multiple times. This never happens in case of `IO` or monix `Task`, or singleton streams, but breaks for streams that have multiple elements.

FS2 defines `Sync` instance for its `Stream`, but it seems to violate this law:

```scala
import cats.effect.{IO, Sync}
import fs2.Stream

object Main extends App {
  type F[A] = Stream[IO, A]
  val F = Sync[F]

  val fa = Stream(1, 2, 3).covary[IO]
  val a1 = 1
  val f = (_: Int) + (_: Int)

  // Inlined Sync.mapSuspendEvaluation with println
  var state = a1
  val evolve = F.map(fa) { a2 =>
    state = f(state, a2)
    state
  }
  // List(3, 5, 8) - state is changed each time
  println(F.map2(F.pure(state), evolve)(f).compile.toList.unsafeRunSync())
  // List(3, 4, 5) - a1 is always the same
  println(F.map(fa)(a2 => f(a1, f(a1, a2))).compile.toList.unsafeRunSync())
}
```
(fs2 0.10.0 RC1 and cats-effect 0.8)

Thoughts?

/cc @SystemFW @alexandru

**Comment by SystemFw** [comment]
Well, at least for fs2 you should _never_ have an impure function passed to `map` and `flatMap` like that. Iirc correctly these two laws were added to ensure stack safety for `IO` in #96, so I'll have to think about the full implications of `Stream` breaking them currently.
@mpilquist thoughts?

**Comment by SystemFw** [comment]
FWIW, if it weren't for stack safety, I would be against these two laws

**Comment by oleg-py** [comment]
One of the possible things to be done is to change this line:
```scala
state = f(state, a2)
```
to this
```scala
state = f(a1, a2)
```
As far as I understand, this will be enough to check that `map` is not evaluated eagerly, but will remove the dependency between subsequent evaluations, so it will hold for streams.

**Comment by mpilquist** [comment]
I think we should consider removing those laws and moving them to unit tests of IO or find a different encoding that doesn’t require suspension. Seems like they enforce a particular implementation that’s not applicable to all syncs. Interested to hear what everyone else thinks though.

I don’t think fs2.Stream should suspend evaluation of map or flatMap.

**Comment by SystemFw** [comment]
> I  don’t think fs2.Stream should suspend evaluation of map or flatMap.

I agree

**Comment by alexandru** [comment]
Hi all,

It is me that added those two laws, as a consequence of this issue: https://github.com/typelevel/cats-effect/issues/92

Basically if there's any case for which `map` or `flatMap` execute the given function without suspending the evaluation (e.g. evaluating `Pure(x).map(f)` directly, like in the provided sample), that makes them stack unsafe, as they can trigger stack overflow errors. See the provided issue.

And `Sync` is all about providing a memory safe `flatMap` and suspending side effects, the two being interlinked, this being its whole raison d'être.

I find it cool when a streaming type like `Iterant` or FS2's `Stream` can implement a type class such as `Sync`. However I don't find this notion of `Sync` being implemented by streams as something that can survive.

For example we're now talking of [Bracket](https://github.com/typelevel/cats-effect/pull/113). Well this proposed `bracket` function has a signature that does not admit streaming because the `acquire` part has to give you precisely one `A` result on evaluation:

```scala
def bracket[A, B](acquire: F[A])(use: A => F[B])
   (release: (A, BracketResult[E, B]) => F[Unit]): F[B] 
```

And the `bracket` on streaming types like FS2 is more like this:

```scala
def bracket(fa: F[A])(use: A => Stream[F, B])
  (release: (A, BracketResult[E, B]) => F[Unit]): Stream[F, B]
```

This is just one example where if we make `Sync <: Bracket`, it would outlaw streaming types.

**Comment by oleg-py** [comment]
> as they can trigger stack overflow errors

This is a Bad Thing™ for sure. But it's not the lack of suspension that causes law violation - `Iterant` suspends `map`s as of now. It's the actual test implementation. With the change I proposed above, it still will fail if `map` is not suspended, as `state` would be mutated eagerly, but will allow streams to pass, as it won't depend on previous mutations.

> Well this proposed bracket function has a signature that does not admit streaming 

I fail to see how. The signature does not require `use` and `release` to be called only once, so by substituting `F[A] = Stream[G, A]`,

```
def bracket[A, B](acquire: Stream[G, A])(use: A => Stream[G, B])
   (release: (A, BracketResult[E, B]) => Stream[G, Unit]): Stream[G, B] 
```

seems possible: acquire a bunch of resources, use them all, then do a bunch of effectful cleanups for each. Streaming for cleanup is probably super redundant, but seems doable.

(I don't expect anybody to use THAT thing directly, but rather in code which is polymorphic in effect types)

Current `fs2.Stream.bracket` manages the lifecycle of the resource, so it's kinda more powerful/useful than the bracket currently being considered (which, as I understand, is `try ... finally` with effect). I think streams can handle both, if their effect type allows it.

**Comment by alexandru** [comment]
@oleg-py if your proposed change still proves that execution is suspended, but relaxes the requirement for `Sync`, then a PR would be most welcome 🙃

I don't think that `bracket` for streams that can emit multiple elements make sense though.
But maybe you're right and I haven't thought this through.

> Current fs2.Stream.bracket manages the lifecycle of the resource, so it's kinda more powerful/useful than the bracket currently being considered

Well, it's a stream. An `IO` / `Task` type has to behave like a call-stack, whereas a stream does not have this limitation.
