### ISSUE TITLE
Port parTraverseN, parSequenceN to CE3

### ISSUE THREAD

**Issue by arosien** [typelevel/cats-effect#1291]
Currently missing.

**Comment by djspiewak** [comment]
I'm going to tag this as a good first issue, since it should be relatively mechanical!

**Comment by TimWSpence** [comment]
I had a quick look at this and it looks like we might want to move `Semaphore` to `kernel` as well for this. Discussion [here](https://gitter.im/typelevel/cats-effect-dev?at=5f9149dc270d004bcfe1d149)

**Comment by Avasil** [comment]
`Semaphore` implementation is good enough to start but since we have a `Queue`, we could use an implementation similar to this one: https://github.com/monix/monix/blob/series/3.x/monix-eval/shared/src/main/scala/monix/eval/internal/TaskParSequenceN.scala

The problem with `Semaphore` implementation is that ALL fibers are started and then they wait asynchronously for a permit.
It wastes a lot of memory and it breaks if the list has too many elements IIRC

**Comment by TimWSpence** [comment]
@Avasil nice, that could be good. But still has the same problem that `Queue` is currently in `std` rather than `kernel`. It seems like we might need some more of these abstractions to live in `kernel`

**Comment by djspiewak** [comment]
The queue implementation is definitely a lot nicer, though the inversion of dependencies here is really annoying. I love having `Queue` (and `Semaphore`) in **std** instead of **kernel**, since they aren't primitives, but `parTraverseN` is compelling. Perhaps it would be best to start with an implementation on `IO` itself while we ponder how best to make it available within **kernel**.

**Comment by TimWSpence** [comment]
> The queue implementation is definitely a lot nicer, though the inversion of dependencies here is really annoying. I love having `Queue` (and `Semaphore`) in **std** instead of **kernel**, since they aren't primitives, but `parTraverseN` is compelling. Perhaps it would be best to start with an implementation on `IO` itself while we ponder how best to make it available within **kernel**.

👍 I'll have a go at that today
