### ISSUE TITLE
Implement an async dispatcher

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1299]
The goal here is to solve the "soviet interop" case (where unsafe code runs you) without requiring `UnsafeRun`. In theory, this is doable with solely an `Async` constraint whenever we have the following kind of situation:

```
+-------------------+
| F[_]              |
|                   |
|  +-------------+  |
|  | Unsafe code |  |
|  |             |  |
|  |  +------+   |  |
|  |  | F[_] |   |  |
|  |  |      |   |  |
|  |  +------+   |  |
|  +-------------+  |
+-------------------+
```

So in other words, you have some effect context, `F[_]: Async`, which sets up some FFI region which needs the ability to unsafely run arbitrary other `F[A]` actions. A good example of this would be a hypothetical `cats-effect-netty` layer, where you would have some outer `F[_]` which instantiates the Netty pipelines and such, within which Netty would need the ability to convert arbitrary `F[ByteBuffer]` values into netty futures (i.e. unsafe running), and those `F[ByteBuffer]` values are themselves effects.

I've been calling this "the soviet enclave special-case". In theory, this should handle *all* "soviet interop" cases except for those which are truly at the end of the world, lacking an "outer" enclosing `F[_]`. For things that are actually the literal end of the world, I'm pretty comfortable just not abstracting, since libraries have no need for this kind of use-case and it only impacts users (who are in control of their specific effect type, and thus can use the appropriate runtime directly).

A quick PoC: https://gist.github.com/djspiewak/f761d0a804b5bb789abe834566239741

**Comment by djspiewak** [comment]
(btw, @baccata and @oleg-py, you may be interested in this)

**Comment by RaasAhsan** [comment]
I think this is going to be one of the most useful abstractions CE3 has yet, on par with `uncancelable`/`poll`. 

If I'm not mistaken, this version of the dispatcher solves the "multiple callbacks" problem as well, right? You would apply `F ~> Future`  to the `F[_]` effect each time you want to produce a new value within the FFI region, looping it back into the runtime. For this situation, I suppose the `Future` is more or less redundant, you really just need a `F[_] => Unit` at the minimum.

**Comment by RaasAhsan** [comment]
Also, recall that the signature of `unsafeRunCancelable` is:
```scala
def unsafeRunFutureCancelable[A](fa: F[A]): (Future[A], () => Future[Unit])
```
There isn't a means of cancellation of the spawned effect in your PoC (which http4s/blaze certainly needs to cancel requests), but it should be fairly straightforward, at the cost of the nice looking `F ~> Future` 😅  Maybe we can define a `CancelableFuture[_]`?

**Comment by djspiewak** [comment]
> There isn't a means of cancellation of the spawned effect in your PoC (which http4s/blaze certainly needs to cancel requests), but it should be fairly straightforward, at the cost of the nice looking F ~> Future 😅 Maybe we can define a CancelableFuture[_]?

I already have this adjusted locally. :-) It's surprisingly tricky though because you basically have to worry about a couple different cases, depending on state. The dispatcher can either have an available worker fiber, or it can be between ticks and you need to place it on a buffer somewhere. If it's the latter case, then canceling just removes from the buffer. If the former then you cancel some fiber. Tricky :-)

> For this situation, I suppose the Future is more or less redundant, you really just need a F[_] => Unit at the minimum.

ScalaJS :-D Can't always block

**Comment by Baccata** [comment]
That is really cool.

In particular, this could facilitate interop with popular in-memory cache implementations from java-land (like caffeine). 

~Putting aside the cancellation concerns, I was wondering whether the functionK targeting `Future` was ideal, as converting it to other Future types (java, guava, twitter's if that's still a thing) would require an EC being present (Future#onComplete), but I assume it's safe to piggyback on the one carried by the Async instance in this case ? Or am I high grossly mistaken ?~

Edit : disregard, hadn't seen the PR

**Comment by djspiewak** [comment]
> Edit : disregard, hadn't seen the PR

:-D To answer your question directly though, I think we can convert to pretty much any type that `IO` can convert to. I was thinking of adding both `CompletableFuture` and `Promise` (ScalaJS)

**Comment by Baccata** [comment]
I've had some thoughts about it and sadly I don't think it'll remove weaver's need for `UnsafeRun` 😞 

Here's a summary of how SBT (and therefore most scala-potent build tools) talks to test-frameworks : 

* It instantiates [a framework](https://github.com/sbt/test-interface/blob/master/src/main/java/sbt/testing/Framework.java#L6), the specific class of which is what you define in your build (`testFrameworks += ...`). It calls the "fingerprint" method to get the qualified name of classes, the children of it should look for in the compilation result. 
* When you call `test`, it instantiates a `runner`, passing possible args you might have passed to it 
* It then passes a list of `taskDefs` to the [runner](https://github.com/sbt/test-interface/blob/master/src/main/java/sbt/testing/Runner.java#L42), which is basically the list of classes it found in the current compile-unit, inheriting from whatever interface you declared as `fingerprint`. Now here's the kicker, the `Runner` isn't really meant to `run` any test, but rather return a list of `Tasks`, which the build-tool decides to call however it wants at its discretion, by passing it a [logger and an observer](https://github.com/sbt/test-interface/blob/master/src/main/java/sbt/testing/Task.java#L36) that should be used to communicate results back to the build-tool. 
* The build tool maps `Tasks` to its own internal model, and runs them depending on what the [user](https://www.scala-sbt.org/1.x/docs/Parallel-Execution.html#Built-in+Tags+and+Rules) has defined in its build. On JVM, the task has a hard synchronous boundary, that I *think* the build-tool uses as a signal that a test suite has finished. 

So the thing is : the test framework doesn't have the control over the absolute "end of the world", the build-tool has, and having control over the outer `F[_]` is required for using `Dispatcher`

I've elected to mostly respect the build-tool in `weaver` and not try to regain control over the "end of the world", so that users' build-wide parallelism settings are respected. However, at the moment, weaver does partially violate the semantics of the test-interface (via educated use of `unsafeRun`) to provide two key features : 

* gathering failures across test suites to display them at the end of the run  
* cross-suite shared resources for performance/efficiency reasons 

Because of this, I think the complete removal of `UnsafeRun` would mean one of two things : 
1. Either the framework would have to fully abide by the test-interface's implied semantics and run each suite in total isolation (which prohibits the two features declared above), considering each of them like a separate `end of the world` with its own IORuntime instance. 
2. Either the framework would have to fully violate the test-interface, run suites itself in a single IORuntime and rely on some ad-hoc protocol (possibly imperatively-mutable queue) to communicate the results back to the test-interface when the build-tool calls upon `Task#execute`. This means the users would lose some of the control they currently have over concurrency via build-settings, and the framework would have to provide some ad-hoc mechanism for the user to control cross-suite concurrency. I've toyed with idea already as I'd very much like for everything to run in a single runtime, but I would prefer for it to be an opt-in rather than something forced onto weaver's users ... 

Obviously if UnsafeRun was removed, I'd go down the second route, but that'd need some more significant work to upgrade, and would increase the disparity between the jvm and the scala-js versions (the two features described above aren't possible in js, cause sbt creates a new js runtime for every task iirc).

**Comment by djspiewak** [comment]
I'm pondering this some more, but I *think* that, generally speaking, test frameworks are a good exemplar of a case where you need multiple "ends of the world". They are, themselves, a meta runtime. So for the same reason that I'm okay with side effecting assertions, I also think that unsafe running is the right approach for tests.

But that creates a bit of a design quandary: is that in scope for CE itself, or should it be punted to the test frameworks? CE could certainly take the philosophy that any abstraction over unsafe running has to be handled by abstractions within the test framework, and that actually wouldn't be the worst thing, but it does mean everyone has to reinvent the wheel.

I'm curious as to some thoughts on this. Weaver, for instance, already has a bespoke ZIO module. Also, given the control over the runtime that a test framework would want to exert (eg ensuring that thread states cannot pollute unrelated tests in the same VM), I'm tempted to say that this sort of thing is inevitable, but I'd like to hear more thoughts.

**Comment by vasilmkd** [comment]
What's the status of this issue?

**Comment by djspiewak** [comment]
It's done. 😃
