### ISSUE TITLE
Proposal: New Effects4s

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#13]
I propose integration with the following type-classes:

```scala
package effects4s

trait Async[F[_]] {
  def async[A](register: (Either[Throwable, A] => Unit) => Unit): F[A]
}

trait Eventual[F[_]] {
  def unsafeExtractAsync[A](fa: F[A])(cb: Either[Throwable, A] => Unit): Unit

  // Optimization on the above for things that execute synchronously
  def unsafeExtractTrySync[A](fa: F[A])(cb: Either[Throwable, A] => Unit): Either[Unit, A]
}
```

The idea would be to implement seamless back and forth conversions in the APIs of participating libraries.

NOTES:

- these should be implemented by data types, like `cats.effect.IO` and shouldn't be extended or anything
- no inheritance, no Simulacrum
- `Async` at most will match the laws of `cats.effect.Async`, or be more relaxed (not sure if I can describe useful laws for it) ... thinking to make `Async[Future]` possible
- project name, organization, maintainers can be discussed
- the plan is of course to eventually convince other projects to implement them
  (I would actually push a proposal for the standard library as well, though anything in the standard library is a tough sell)

Thoughts?

**Comment by djspiewak** [comment]
Relaxing the laws of the effects4s `Async` (or at least, relaxing the stack-safety constraint) does indeed make this *possible*, so it just comes down to exactly what we want here.

I have a couple concerns:

- This would add another dependency to cats-effect, and indeed *everything* downstream, which is a bit of a significant load to take on.  The bar for stability on effects4s would indeed be extremely high, and given the comparatively large number of typeclasses in the library, I'm concerned on that front.
  + We could potentially mitigate this using `"provided"`, basically opening the door for downstream projects to ignore effect4s if they so choose, or if they need the conversions, bring in the dependency explicitly.
- If the point of effects4s is interop, why do we need more than just `Async`?
  + As a sidebar, I find it pretty unlikely that you'll be able to define a useful set of laws which simultaneously characterize lazy effect types (like `Task` or `IO`) *and* eager, memoizing containers like `Future`, but I admit that would be quite cool
- I'm not particularly fond of `unsafeExtractTrySync`, since it forces you to provide two handlers.  Effectively, it's like the inconvenience of *both* the synchronous and the asynchronous extractors, all in one.

**Comment by alexandru** [comment]
I've thought more about it today - currently not very enthusiastic about this. Closing this issue for now.

> We could potentially mitigate this using "provided"

Does this work? It would be awesome if it did, but I tried doing this with `cats-core` by means of macros (to avoid bytecode signatures that would trigger `ClassNotFoundException`), but whenever a compiler error happens, it starts triggering really nasty exceptions -- so when the compiler doesn't find some method you want to call on a type, it probably starts looking for implicit conversions, which triggers those macros, which then trigger classpath errors.
