### ISSUE TITLE
TestContext deadlock

### ISSUE THREAD

**Issue by SystemFw** [typelevel/cats-effect#1331]
```scala
package cats.effect

import scala.concurrent.duration._
import cats.syntax.all._

class TestContextSpec extends BaseSpec {
  def io: IO[Unit] =
    for {
      fiber <- IO.unit.foreverM.start
      _ <- IO.sleep(100.millis)
      _ <- fiber.cancel
    } yield ()

  "tc works" in real {
    io.as(success)
  }

  "tc deadlocks" in ticked { implicit ticker =>
    io must completeAs(())
  }
}
```

**Comment by djspiewak** [comment]
I could use some help from @alexandru on this one, if you have some time. I think I have a vague idea of what might be causing it, but `TestContext` is black magic.

**Comment by RaasAhsan** [comment]
I'm pretty sure this is a fairness issue where the spawned fiber is just continuously looping. I tried inserting a `cede` and that doesn't fix it either because the internal task queue is ordered by target time execution. Cedes will preserve the current execution target time, but the sleep is scheduled to happen at `100 millis`, so it just keeps on looping on the fiber too.

**Comment by djspiewak** [comment]
Can confirm (a year late) that Raas' opinion is correct: it is indeed a fairness issue, and fundamental to `TestContext`.

**Comment by alexandru** [comment]
Hi, so what's the problem?

`TestContext` simulates an `ExecutionContext` that's manually triggered to execute all pending `Runnable` via `tick`, or to execute all pending delayed runables via `tick(300.millis)`. It has however limited utility, since in order to have `IO.sleep(300.millis)` complete, then somebody has to `tick(300.millis)` on the `TestContext`, which is the whole point of using it.

**Comment by alexandru** [comment]
NOTE — in order to simulate time passing in an automated fashion, another idea would be to do something like ...

```
while (taskNotComplete) context.tick(100.millis)
```

What something like this would do is to advance its internal timer in 100 millis increments, eventually triggering all pending tasks.

Not sure if this is a good idea.
