### ISSUE TITLE
Identify and correct runtime issues on ARM

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1363]
@vasilmkd ran a test run under ARM and found several issues. We should fix those. We should also find a way to set up a runner for the build which allows us to test under ARM with regularity.

Oh also, to be clear, I think ARM64 should be the priority. Very few real systems run ARM these days, and those which do are pretty safely out of scope. Power-conscious server-side applications, tablets, and laptops (including the forthcoming Apple hardware) are all using the ARM64 architecture, and thus this should be our target.

**Comment by djspiewak** [comment]
For the record, this is surprisingly useful: https://gist.github.com/humbertodias/6237f80df9a4bccf98be298057a82cf2

**Edit** I got more mileage out of this one, though: https://translatedcode.wordpress.com/2016/11/03/installing-debian-on-qemus-32-bit-arm-virt-board/

**Comment by djspiewak** [comment]
As a bullet point, I was able to run the entire test suite (I just ran the JVM) on ARM64 and everything passed. Is it perhaps nondeterministic? I only had two cores on the instance I used.

**Comment by vasilmkd** [comment]
I ran it on a 16 thread aws instance, and I could observe it more often, but they are definitely flaky.

`ContSpec`, `DefaultContSpec` and `DeferredJVMParallelization{1, 2, 4}Spec`.

**Comment by djspiewak** [comment]
> I ran it on a 16 thread aws instance, and I could observe it more often, but they are definitely flaky.

I'll try a larger instance then

**Comment by djspiewak** [comment]
Was able to reproduce the issues with a 16 core setup: https://gist.github.com/7a03365762cd9e361a39d25abb3151bf

**Comment by djspiewak** [comment]
Further update: I've confirmed this is a memory visibility issue. Adding `@volatile` to `canceled` fixes all build errors.

**Comment by djspiewak** [comment]
Here's a relevant SO question suggesting our use of memory barriers is valid: https://stackoverflow.com/questions/29846319/compareandset-memory-effects-of-unsuccessful-operations The test program btw does appear to terminate reliably on ARM64.

**Comment by RaasAhsan** [comment]
Here's my take on this right now. We're making the following assumptions:
1. The ARM64 JVM implementation respects the JMM.
2. The JMM guarantees that a non-volatile write to A that takes place before a volatile write to B is visible to a thread T if T reads B before reading A. I've confirmed this on countless SO answers and blog posts that do this. Unfortunately, there is no primary source that claims this. The spec and its authors are pretty laconic, but you _can_ derive this from the synchronization order and the happens-before order.
3. Atomic variable operations have the same effect as their corresponding volatile operations. The javadoc for the `atomic` package says as much and `Java Concurrency in Practice` does as well. I think we can assume that the result of the CAS has no bearing on the presence of the barrier since nobody says otherwise.
4. CE3 code is correctly synchronizing on `suspended` and `canceled` with respect to the JMM, but maybe we're getting lucky on x86 because of its strong memory model.

If any one of these are false, then that could explain what we're seeing. I think it's worth finding a minimized example that reproduces this behavior, either by building an example from the ground up or ripping code out of `IO` until we can remove it.

I also don't want to discount the possibility that there is a race _elsewhere_ in the codebase. There's a lot more to the async state machine than just `canceled` and `suspended` so it's probably smart to keep a broad perspective here before we do something crazy to fix the issue. It could very well be that marking `canceled` as `volatile` makes some races a lot less likely because cancellation can be observed earlier rather than later, or something like that.

I'm going to try to pursue minimizing our code and seeing where that takes us, but first I need to get an AWS account :)

**Comment by djspiewak** [comment]
Raas wins the internet today for correctly using the word "laconic".

**Comment by djspiewak** [comment]
Given variables `a` and `B`, where `B` is volatile, consider the following pair of threads:

```
// thread 1
write(a);
cas(B);
```

```
// thread 2
cas(B);
read(a);
```

Given that **thread 1** has completed its `cas(B)` instruction, is it *guaranteed* that the `read(a)` in **thread 2** will see the value written in `write(a)`, given that these are the only two threads interacting with `a` and `B`?

**Comment by simonis** [comment]
I've answered on the Gist which pretended to have a simple reproducer for this issue why at least that reproducer behaves in a completely JMM and API specification conformant way:

https://gist.github.com/RaasAhsan/8e3554a41e07068536425ca0de46c9e8#gistcomment-3524340
