### ISSUE TITLE
Add iteration combinators to IO

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1473]
- `foreverM`
- `untilM`
- `whileM`
- `iterateWhile`/`iterateUntil`
- others-that-i've-probably-forgotten

Should have the same signatures and semantics as their counterparts within cats core.

**Comment by pkowalcze** [comment]
I'd like to give it a go, if it's ok with you

**Comment by djspiewak** [comment]
Do it!!

**Comment by TimWSpence** [comment]
@pkowalcze are you still planning to work on this? If so that's fantastic! :) Let me know if you need a hand with anything.
If you're not then I might pick this up in a couple of days.

**Comment by pkowalcze** [comment]
@TimWSpence Very sorry for the delay, I'm going to get it done as soon as possible. Could you verify that I understood the intent of this task correctly? Is it to have something like:

```
def untilM[G[_], A](f: IO[A])(cond: => IO[Boolean])(implicit G: Alternative[G]): IO[G[A]] = f.untilM(cond)
```

in the `IO` object?

**Comment by TimWSpence** [comment]
Hey @pkowalcze no worries at all!! :)  Yes, exactly - it's so we have convenient syntax like `IO.untilM` instead of `Monad[IO].untilM`

Note that we want to be sure that it has the same semantics as the methods defined on the monad instance for `IO`. I _think_ the best way to do that is
```
object IO {
  def untilM(...) = _asyncForIO.untilM(...)
  
   def foreverM(...) = _asyncForIO.foreverM(...)

  //etc
}
```
so the implementation on `IO` just forwards to the `Monad` instance. @djspiewak might have a better idea though

**Comment by djspiewak** [comment]
I think it's better to make these instance methods, rather than putting them on the object. Basically, take the following example:

```scala
IO.println("Hello, World").foreverM
```

Right now, that example requires `import cats.syntax.all._`. Make it so that example (and others like it involving Cats iteration combiantors) works without requiring the import. That's the task!
