### ISSUE TITLE
CE3: Document that the requirements for `Resource.use` have changed

### ISSUE THREAD

**Issue by mcanlas** [typelevel/cats-effect#1492]
Was playing around with the upgrade to `M4` and noticed that the following doesn't work anymore.

```scala
def makeAndUse[F[_]](implicit Sync[F]): F[Unit]
  Resource
    .make(F.unit)(_ => F.unit)
    .use(_ => F.unit)
```

The call to `use` is now looking for `MonadCancel[F, Throwable]` which `Sync[F]` does not satisfy.

Offline chat with @RaasAhsan and @djspiewak indicates this is by design.

Maybe there are improvements that could be made to the migration guide and documentation indicating that this change happened and what the remedy/migration would be for the first line.

For the record, changing to `Async[F]` works since `Async` also satisfies `MonadCancel` in this example.

**Comment by djspiewak** [comment]
The `Sync with MonadCancel` bit is a rather significant usability wart in the hierarchy, IMO. @oleg-py ran into something similar in monix-catnap. I'm becoming increasingly convinced that we need something above `MonadCancel` which lacks `canceled` but has everything else, so you can write cancelation-safe code without *forcing* the underlying type to support cancelation.

**Comment by RaasAhsan** [comment]
> I'm becoming increasingly convinced that we need something above MonadCancel which lacks canceled but has everything else

The issue here becomes lawfulness, right? If you don't have `canceled`, you can't say much if anything about `onCancel` or `uncancelable`. I think that's purely academic though and not of much interest to the majority of users :) 

Addressing this in the hierarchy seems to be the right approach (writing cancellation-safe code w/o having to deal with cancellation), but would be nice to get a refresher on why the `Resource.Bracket` disjunction was removed
