### ISSUE TITLE
Side channel report on failed handleErrorWith

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1548]
I'm thinking we should probably side channel report the original failed error here:
https://github.com/typelevel/cats-effect/blob/1bd09ed0b2481267c3d7e2d760001200bf6e796c/core/shared/src/main/scala/cats/effect/IOFiber.scala#L1059

**Comment by djspiewak** [comment]
That's basically what `failed` does though. Side-channeling fatal errors is really tricky because you can't reliably allocate. `failed` actually does one better than this and reliably side-channels to stderr, then *attempts* to relocate the error back to the `unsafeRun`* call-site. In most cases, this should succeed, which provides the UX that I think most people would expect if they don't think about it too hard.

**Comment by RaasAhsan** [comment]
Sorry, I'm not sure if I clearly described the motivation, take a look at the whole function:
https://github.com/typelevel/cats-effect/blob/1bd09ed0b2481267c3d7e2d760001200bf6e796c/core/shared/src/main/scala/cats/effect/IOFiber.scala#L1054-L1061

That's the continuation for error handlers: if invoking the error handler itself produces an error, we relocate _that_ error back to the runloop, which is consistent with `ApplicativeError` laws. But the original error `t` we had is more or less thrown away at this point (`t` is shadowed by the `NonFatal` pattern argument). I was thinking we could log the original one

**Comment by RaasAhsan** [comment]
Maybe this might not make sense at all, now that I think about it. Functions like `adaptError` are implemented in terms of `handleErrorWith`, but we don't want to report in that case. The user should be responsible for catching errors for the handler if they need to. I think we're good here then
