### ISSUE TITLE
IO#foreverM and IO.never are inconsistent

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1660]
The former returns `IO[Nothing]` while the latter is of type `[A]IO[A]`. This works out to be the same thing in most cases (e.g. the expression `IO.never` will infer to have type `IO[Nothing]`) but there are some differences. The reason `IO.never` takes a type parameter is to make it easier to ascribe a particular type to help the type inference along in some cases. Rather than needing to do something like `IO.never: IO[Unit]`, you can just do `IO.never[Unit]`. However, at least in the case of `foreverM` on 2.12, it appears that this trick causes *its own* set of type inference issues. See the discussion around #1589 

We should either find a way to make `foreverM` take a type parameter again, or we should remove the parameter from `IO.never` and make sure that we're not causing other problems.

**Comment by wemrysi** [comment]
How about `foreverM[A]: IO[A]` and `foreverM_: IO[Nothing]` (and analogously for `never`)?

**Comment by djspiewak** [comment]
I think the problem is that `foreverM[A]` means that the type inference in the most common case doesn't work. 😔 #1589 was where we first hit this. Also wouldn't the cats convention for `foreverM_` be `IO[Unit]`?

**Comment by wemrysi** [comment]
> I think the problem is that foreverM[A] means that the type inference in the most common case doesn't work.

Yeah, maybe `foreverM: IO[Nothing]` then. My main thought was whether having both variants is useful for ergonomics (having the unadorned `foreverM` be whichever form is most generally applicable). If the cases where ascription is necessary aren't as common, maybe we just settle for ascription in order to avoid bloat.

> Also wouldn't the cats convention for foreverM_ be IO[Unit]?

It would so I guess that's out, we need a suffix that evokes "just tell me the answer!" 😃
