### ISSUE TITLE
Provide access to the default blocking EC from Async[F]

### ISSUE THREAD

**Issue by catostrophe** [typelevel/cats-effect#1762]
1. There's a recommendation to use a single blocking pool created as a resource on App startup.
2. There's a method in `Sync` that allows suspending a computation on the blocking pool. Although it's just a hint for the runtime, this implies that some blocking pool will probably be available (except for running simple single-threaded IOs such as `SyncIO`).
3. There's a method in `Async` for extracting the current EC from the context of F[_].

My proposal is to add a method to `Async` for extracting the default blocking pool somehow in a similar way.

It may be implemented as
```scala
def deferBlocking[A](fa: => F[A]): F[A]
def blockingExecutionContext: F[ExectionContext] = deferBlocking(executionContext)
```
or in a different way.

This will allow users to avoid manually managed blocking pools and use the default one when needed.

**Comment by djspiewak** [comment]
Hmm, this was something that was considered and then explicitly rejected in favor of keeping the API simpler and avoiding thread pool leaks. Can I understand the use-cases a bit more? If we go this route, then we *definitely* need to push the 3.0.0 final release date, because we would need another month at least to let the new axioms marinate.

**Comment by catostrophe** [comment]
I liked the new simple API with `Sync[F].blocking(...)`. And actually, I did manage to migrate my use-cases of blockers (`F.evalOn(delayedBlockingComputation(), blocker)`) to wrapping impure blocking code in `F.blocking { ... }` at the deepest level of integration.

But my concern is that I cannot be sure that this holds true for some IO-monad that implements the CE3 interfaces:
```scala
F.blocking(blockingImpureComputation()) <~> F.evalOn(F.delay(blockingImpureComputation()), internalBlockerEC)
```

This is implied, but we don't have laws that force `F.blocking` to behave in the same way as `evalOn` does, with all those guarantees regarding nested scopes that prevent tasks from sudden shifting to a wrong pool. Moreover, without access to the `internalBlockerEC` we cannot express such a law.

IMO, the API should have provided `blockingEC` as a base method, while `blocking` should have been expressed via it, `delay` and `evalOn`. This is probably useless for an end-user. But it would make the API more lawful.

**Comment by djspiewak** [comment]
> This is implied, but we don't have laws that force F.blocking to behave in the same way as evalOn does

We do actually!

```scala
(F.executionContext <* fa) <-> (fa *> F.executionContext)
```

We have this law for any `fa`, including `F.blocking(...)`. Honestly, one of the motivations for `blocking` taking a `=> A` rather than a `F[A]` is precisely to avoid the problems you're talking about: it's *impossible* for any deeply nested code within a `blocking` action to mess up the current thread pool, if only because `blocking` simply doesn't give you that expressive power. Same with `interruptible`, which *can't* really be expressed in terms of an `F[A]`.

So I think the API as it stands is actually just as lawful as what we would have if we encoded in terms of `blockingEC`, but the expressive power is more constrained while leaving a little more flexibility to datatype implementors.

**Comment by catostrophe** [comment]
> We do actually!
> 
> ```scala
> (F.executionContext <* fa) <-> (fa *> F.executionContext)
> ```

Hmm, ok. We do test that `fa` doesn't leak its EC. Agree.

But how do I know that `blocking` actually switches to some blocking pool?

**Comment by djspiewak** [comment]
> But how do I know that blocking actually switches to some blocking pool?

We don't! This is intentionally left up to implementors. There's probably no way around this though. Honestly, even if we exposed `blockingEC`, we would *still* be in that situation since there's nothing preventing implementors from defining `blockingEC == executionContext`.

**Comment by joroKr21** [comment]
> Honestly, even if we exposed blockingEC, we would still be in that situation since there's nothing preventing implementors from defining blockingEC == executionContext.

I guess that's exactly what happens on Scala.js

**Comment by catostrophe** [comment]
@djspiewak thanks for clarification!

Probably the last scenario that comes to my mind: some TF library provides a builder that requires an explicit blocking EC for performing blocking io operations.

To integrate with this lib I have to manage a EC manually and cannot use the default blocker. This is doable but we cannot keep only 1 blocking pool for  an app.

**Comment by djspiewak** [comment]
> To integrate with this lib I have to manage a EC manually and cannot use the default blocker. This is doable but we cannot keep only 1 blocking pool for an app.

I mean, you technically can via `Dispatcher`, but I'm not convinced it's going to be a good idea. It certainly will have some performance overhead.

In general though, TF-enabled libraries shouldn't be taking explicit ECs unless they absolutely need them (e.g. for interop with external ecosystems). In this case, the `Async[F].executionContext` function is a far more preferable way of encoding it, with `evalOn` being used to scope things internally. I would also suggest that, in any case where an external system is requiring an `ExecutionContext` (or similar), you're *probably* going to be better served by explicitly creating one yourself (or having the library do it internally), since the needs and expectations around these kinds of pools vary a lot, and it's not necessarily correct to use the compute pool or the blocking pool as-is.

**Comment by catostrophe** [comment]
Ok. Thanks for the explanation.
