### ISSUE TITLE
Remove support for 2.10?

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats-effect#179]
Scala 2.10 is very old and hardly supported version nowadays, it was released in 2012 and is definitely EOL. Neither fs2, nor http4s or doobie support it and other libraries inside the ecosystem dropped support some time ago as well (e.g. circe, monix). I don't see a really good reason to keep supporting it, unless we can point to some statistic that clearly states otherwise. It's been known to cause some odd problems and it's burned me a few times in the past (i.e. cases where 2.12 and 2.11 worked without problems, but 2.10 failed with compiler errors).

**Comment by alexandru** [comment]
I would have preferred for `cats-effect` to provide the same level of support as Cats.

That said in Monix I dropped support for 2.10 because it was just too painful for me to maintain it and I don't have the budget for it.

So if the other maintainers are on board, I'm fine with it, because keeping support has a cost that somebody has to pay.
