### ISSUE TITLE
Allow suppressing default IOApp cancellation behavior

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#1796]
For apps that serve as e.g. REPLs, being cancelled by `Ctrl+C` doesn't seem like abnormal behavior, so I think there should be a way to opt out of the current behavior of printing a stack trace of `CancellationException`.

I have worked around this by calling the default `main` myself and catching that exception: 

```scala
object Main0 {

  def main(args: Array[String]) =
    try new Main().main(args)
    catch {
      case _: CancellationException => ()
      case e: Throwable            => throw e
    }
}
```

but that obviously has the disadvantage of having to manually wrap the IOApp instance and relies on an implementation detail.

I would suggest something like adding a non-final `def handle(e: Exception): Unit` / `def handle(e: CancellationException): Unit` method in IOApp, throwing by default. Open to other suggestions for solving this :)

**Comment by djspiewak** [comment]
Are we printing the cancellation exception unconditionally whenever the shutdown hooks are hit? I'm not quite clear on what's going on here. If that's the case then we should stop. The purpose behind the `CancellationException` was to handle the scenario where `IO#unsafeRunSync()` (or similar) was being called directly. I'm tempted to say that the right approach is to just unconditionally swallow the exception in `IOApp`, since it simply isn't useful.

**Comment by vasilmkd** [comment]
I have worked on this code path before, I'll see what's going on.
