### ISSUE TITLE
Timer as a Resource

### ISSUE THREAD

**Issue by durban** [typelevel/cats-effect#207]
Now that there is a `Resource`, should `Timer` be one? It seems like something that can be allocated/released ... does this makes sense?
```scala
def mkTimer[F[_]](ec: ExecutionContext, sch: ScheduledExecutorService): Resource[F, Timer[F]] =
  // ... shut down threadpools in `release`
```
Or could we even create the threadpools?
```scala
def executionContext[F[_]: Async]: Resource[F, ExecutionContext] =
  // ... shut down in release
def scheduler[F[_]: Async]: Resource[F, ScheduledExecutorService] =
  // ... shut down in release
def mkTimer[F[_]: Async]: Resource[F, Timer[F]] = for {
  ec <- executionContext[F]
  sch <- scheduler[F]
} yield Timer.derive(F, IOTimer(ec, sch))
```
(If it makes sense, I'm willing to work on something like this.)

**Comment by mpilquist** [comment]
Would `Timer[IO]` still be available implicitly given an implicit EC and with a single daemon thread scheduled executor service on the JVM? I discussed this with @alexandru at one point and he convinced me we were okay with a single JVM wide `ScheduledExecutorService` by default.

Anyway, I'm 👍 on this assuming we're not changing the current default `Timer[IO]` instance.

**Comment by durban** [comment]
I admit I didn't think this through very much yet. Besides the things @alexandru mentions, it now occurs to me, that `Resource` seems useful for things which are used "explicitly", while `Timer` mostly (?) seems used implicitly. So maybe this is not such a good idea after all ...

(But yes, I didn't want to change the current `Timer`s, just provide a utility / utilities for working with `Resource`.)

Btw, what's recommended for `Timer` if I need multiple thread pools and shifting between them? Should I have multiple `Timer`s? Or should I have one `Timer` with the "default" thread pool, and additional `ExecutionContext`s for the others?

**Comment by alexandru** [comment]
I would recommend the later. Different `Timer` instances can be used in the code base (which is why it isn't a type class), but for shifting between thread pools I think it would be better to just work with `ExecutionContext` directly. But it's a matter of preference really.

**Comment by durban** [comment]
I admit, I'm not completely up to date regarding `ContextShift`, but it's still backed by a thread pool, which might need shutting down, right? In which case, `Resource` still might make sense (if it originally did).

Also, the scaladoc says, that it is _not_ a type class, but also refers to "the default execution environment of `F`". Which seems a contradiction ... but I might be missing something ...

**Comment by alexandru** [comment]
@durban the instance provided by `IO.contextShift` is backed by `ExecutionContext`, which cannot be shut down.

You can build your own instances, backed for example by Java’s ExecutorService and that can be shut down. In that case wrapping those in a Resource might be desirable and it’s actually what we should encourage people to do.

But Cats-Effect provides no such resources. And I’d rather see micro-libraries like Linebacker do it.

And the functions themselves that use ContextShift (like IO.start) cannot use a Resource for obvious reasons ... you don’t want functions like `start` to shut down your thread-pool, this being an application-wide concern, not a local one.

ContextShift is _almost_ a type class. In most cases you work with a default, but because if the 1:1 multi-threading of the JVM, where we’ve got fat processes that end up using multiple thread-pools, there are cases in which we want to override that default so we cannot guarantee coherence.

It’s also lawless. There’s not much we can do to express “yields control back to the runloop or thread-pool” in laws.

Btw in Monix the default ContextShift will be a pure value that does not depend on a thread-pool being available on its creation, this being the result of how a `Scheduler` gets injected on Monix’s Task execution. And in our new `IOApp` too we have a “default” ContextShift that simply piggybacks on Scala’s `global`. You can override it with your implementation but it has to be available for the whole duration of the app, since the logic in IOApp itself depends on it.

**Comment by alexandru** [comment]
Or in other words, wrapping thread-pools in `Resource` is a great idea, however we’ve got no use for it in Cats-Effect’s API and I’d rather see such utilities in a micro lib.

**Comment by ChristopherDavenport** [comment]
@durban I would happily take this on in the scope for [`linebacker`](https://github.com/ChristopherDavenport/linebacker). Could you create an issue on the repo and we can built that up. The introduction of `contextShift` means that API will be able to shift around quite a bit to support thread pools and execution contexts while still allowing cats-effect api surfact to remain small but directly dealing with the final concern of executing on a specific pool.
