### ISSUE TITLE
Add IO#timeout and Concurrent.timeout

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats-effect#209]
The ScalaDoc for IO.race has a great example implementation of time outs. Let’s add that to IO and Concurrent so folks don’t copy/paste it.

**Comment by alexandru** [comment]
I'm 👍 on adding to `IO` and 👎 on adding to `Concurrent`, unless we're talking about a helper defined on the companion.

The problem with `timeout` is that you need a `Timer` for it. Which is fine for `IO`, but Monix's `Task` doesn't need a `Timer`, as `Timer` is backed into `Task`.

So it's fine if it's a helper on `object Concurrent`, but not an operation on the `Concurrent` class because that needs laws and adds syntax (speaking of which our `cats.effect.implicits` is outdated).

**Comment by oleg-py** [comment]
@alexandru what about adding it to `Timer` then?

**Comment by alexandru** [comment]
@oleg-py well it kind of pollutes its API. 

For any `F[_]` its implementation can piggyback `race` and `raceWith`, I don't think there's much room for optimizations by overloading (unless you've got a `sleep` provider other than `Timer`), so the `Concurrent` companion object is IMO a good fit.

**Comment by mpilquist** [comment]
Companion sounds good to me.

**Comment by alexandru** [comment]
This was solved in #214.
