### ISSUE TITLE
Should Ref constructors have curried type parameters?

### ISSUE THREAD

**Issue by oleg-py** [typelevel/cats-effect#210]
When creating a `Ref`, we're always supply a default value, but we have to specify a type explicitly, e.g. `Ref[IO, Int](0)`.

I think it would be more convenient if I could write `Ref[IO](0)` or `Ref[IO].unsafeCreate(0)`, letting the inference do its job.

**Comment by alexandru** [comment]
👍 Cats has been doing it and I've been doing it as well in Monix.

Also see: https://typelevel.org/cats/guidelines.html#partially-applied-type-params

Checkout [EitherT](https://github.com/typelevel/cats/blob/v1.1.0/core/src/main/scala/cats/data/EitherT.scala#L279) for inspiration. Because that's an `AnyVal` no boxing should be involved (but I haven't checked TBH).
