### ISSUE TITLE
Bracket instances for transformers

### ISSUE THREAD

**Issue by durban** [typelevel/cats-effect#216]
For the various transformers (`Kleisli`, `OptionT`, ...) there are `Sync` instances (if the inner `F` has a `Sync` instance). There are also similar `MonadError` instances for them. However, there doesn't seem to be similar `Bracket` instances. Is it not possible to define them, or are they simply missing?

**Comment by alexandru** [comment]
I think the reason there are no instances is because defining instances for these monad transformers is in general complicated. I've lost many hours solving problems for the available instances.

Also it might be challenging because you can't rely on the stack safety of `Sync` when all you have is `Bracket`. Not sure if that's important or not.

But try it out. Maybe we can.

**Comment by djspiewak** [comment]
I would say that this is best tried and experimented with! PRs very much welcome.
