### ISSUE TITLE
Effect.runAsync is unclear what the contract is

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats-effect#219]
The comment says:
```scala
  /**
   * Evaluates `F[_]`, with the effect of starting the run-loop
   * being suspended in the `IO` context.
   *
   * Note that evaluating the returned `IO[Unit]` is guaranteed
   * to execute immediately:
   * {{{
   *   val io = F.runAsync(fa)(cb)
   *
   *   // For triggering actual execution, guaranteed to be
   *   // immediate because it doesn't wait for the result
   *   io.unsafeRunSync
   * }}}
   */
```

Our toy implementation on LTask (basically `() => Future[A]`) is:
```scala
def runAsync[A](fa: LTask[A])(cb: Either[Throwable, A] => IO[Unit]): IO[Unit] =
  IO(fa.run(ec).onComplete { r =>
    cb(Conversions.toEither(r)).unsafeRunAsync(Callback.report)
})
```
which indeed seems to match the comment: the call to onComplete is suspended, shouldn't fail, and should return almost immediately (actual work is run in the ExecutionContext).

However, the confusion comes when we pass a `cb` that could fail or that we want to observe the result from. That IO seems unrelated to any laws.

If my `cb` is something like `_ => IO.raiseError(new Throwable("foo"))` I guess that what happens to that `foo` is undefined?

I am asking because I was looking at this method to put a `toIO` on `Effect`

```scala
trait Effect[F[_]] extends Async[F] {
  def toIO[A](f: F[A]): IO[A] =
    for {
      defA <- Deferred[IO, Either[Throwable, A]]
      _ <- runAsync(f)(defA.complete)
      either <- defA.get
      a <- IO.fromEither(either)
    } yield a
}
```

Adding such a `toIO` to `Effect` seems like a good idea to me since it can be optimized beyond this in many cases.

It also means that you can convert one effect to another kind of effect using liftIO plus the above method.

**Comment by johnynek** [comment]
Thinking about this more, it seems that `toIO` could be an alternate formulation equivalent to `Effect`. If we had `toIO` we could implement runAsync by converting to IO and calling there. We might not need to call runAsync directly to implement `toIO`.

For instance, I think for `LTask` we could do 
```scala
IO.async { cb => run(ec).onComplete { t => cb(toEither(t) } }
```

It seems to me worthwhile to add `toIO` to `Effect` since it is currently equivalent to the methods we have now (no more or less powerful).

This also came up here: https://github.com/typelevel/cats-effect/pull/213/files#r187513230 cc @rossabaker

**Comment by alexandru** [comment]
> However, the confusion comes when we pass a cb that could fail or that we want to observe the result from. That IO seems unrelated to any laws.

If the callback fails, it's a protocol violation and the behavior is undefined.

Basically if the callback fails, there's nowhere to stream the error to, because you're supposed to call the callback for errors and the callback just failed, so you no longer have a callback that you can use. What happens next is implementation specific. You could log it to stderr for example, but that's implementation specific and the other problem is that you can't really catch that error in all cases.

Basically the callback shouldn't fail. If it does, that's the user's problem.

You also cannot observe the result because you no longer have the means to do it. In order to observe the result of an asynchronous process you have to register a callback somewhere. Well we can't register another callback to observe the result of the first callback, that would be overkill.

Basically `IO` is there in order to have the API more pure than plain, impure `Either[Throwable, A] => Unit`, but there's no other reason. Just as if it were an `Either[Throwable, A] => Unit`, you can't observe errors from it, you can't back-pressure on it.

And it cannot be an `F[_]` instead of an `IO` because `F[_]` would seriously complicate issues for no good reason, since all we want with the result of that callback is the ability to trigger `unsafeRunSync` on it.

**Comment by djspiewak** [comment]
I'm going to close this issue, as it seems clear that version 3.0 will not have any variant of `runAsync` on the typeclasses.
