### ISSUE TITLE
IO.bracket introduces async boundary

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats-effect#233]
```scala
scala> Effect[IO].runSyncStep(IO.unit).unsafeRunSync
res7: scala.util.Either[cats.effect.IO[Unit],Unit] = Right(())

scala> Effect[IO].runSyncStep(IO.unit.bracket(_ => IO.unit)(_ => IO.unit)).unsafeRunSync
res8: scala.util.Either[cats.effect.IO[Unit],Unit] = Left(IO$1422818528)
```

This is problematic with FS2 when running on Scala.js. For example, when interpreting pure streams, FS2 uses `IO` and `unsafeRunSync`, but that now fails on Scala.js due to the use of `IO.bracket`. Before we had `Bracket`, FS2 used `attempt.flatMap` when compiling streams to an effect type. Interpreting pure streams would result in an `IO` that was safe to call `unsafeRunSync` on Scala.js.

Ideally, we'd have a stack safe `SyncIO` and FS2 would just use that for interpreting pure streams. In lieu of that, is there something we can do to `IO.bracket` such that it avoids an async boundary unless required?

To see the issue with FS2, take a look at https://github.com/functional-streams-for-scala/fs2/pull/1143

**Comment by alexandru** [comment]
So `bracket` relies on `onCancelRaiseError` and unfortunately its implementation is implemented via `IO.Async`. We can't really workaround it. `IO`'s implementation is the simpler version, because the Monix version is described entirely via `Async`, [see PR](https://github.com/monix/monix/pull/674).

The run-loop for example is using an internal `IOConnection` that aggregates cancelable tokens, which doesn't even get created until after the first `Async` state happens. We basically need the `Async` state because that's the way to tap into the cancellation mechanism, that's the way to access `IOConnection`, which we need in order to register a cancellation handler.

The execution itself is trampolined, so it actually executes on the same thread. But we can't know that in advance. Although there' might be tricks we could do. 

_Proposal 1:_ we add a boolean flag into the `Async` node that instructs the run-loop that the code is safe to execute synchronously. 

_Proposal 2:_ on top of Scala.js we could start the execution with a callback that sets a variable and after `unsafeRunCancelable` we check that variable. If it was a trampolined state, then the variable should be set. Otherwise we trigger `cancel` and throw the error.

The nice thing about this is that it doesn't impact the JVM, but the downside is that we might end up with code being executed that was never supposed to execute, correctly then via a runtime error of course.

_Proposal 3:_ we introduce `SyncIO` right now. But to be honest, this would probably require breaking changes, because if we have `SyncIO`, then its usage should replace `IO` in all type-classes, as usage of `IO` will no longer make sense. So maybe for a version 2.

**Comment by alexandru** [comment]
So given this is relevant only for Scala.js, I believe that Proposal 2 is probably the best.

Will do a PR.

**Comment by alexandru** [comment]
Here it is: https://github.com/typelevel/cats-effect/pull/234
