### ISSUE TITLE
Dispatcher[IO].use does not work with unsafeRunAsync

### ISSUE THREAD

**Issue by Euse** [typelevel/cats-effect#2380]
### Versions
- Cats Effect: 3.2.9
- Scala: 2.13.0

### Description

When I use Dispatcher[IO].use and then perform an unsafeRunSync, code is executed correctly. Here's a working example:

``` scala
object HelloWorld extends App {
  Dispatcher[IO].use(d => IO(d.unsafeRunSync(IO(println("HelloWorld"))))).unsafeRunSync()
}
```

But if you do the same with unsafeRunAsync nothing is printed on the console.

**Comment by armanbilge** [comment]
What are you changing to `unsafeRunAsync`? The inner (first) or outer (second) `unsafeRunSync`?

Because `unsafeRunAsync` doesn't backpressure, my guess would be that the dispatcher is being shutdown before the println executes.

**Comment by Euse** [comment]
``` scala
object HelloWorld extends App {
 Dispatcher[IO].use(d => IO(d.unsafeRunSync(IO(println("HelloWorld"))))).unsafeRunAsync(_ => ())
}
```
Is at the end of the program. Dispatcher does not have unsafeRunAsync

So is this the expected behaviour? Because I don't see any mention to this in the documentation.

**Comment by armanbilge** [comment]
Thanks for clarifying!

> So is this the expected behaviour? Because I don't see any mention to this in the documentation.

Yes. This is the difference between synchronous and asynchronous computation.

Your first example works because `unsafeRunSync()` blocks (waits) until the `IO` completes, then your app terminates. 

But, the second example using `unsafeRunAsync()` schedules the `IO` to run asynchronously and then returns immediately (without waiting), and your app terminates before the `IO` executes.

You should try using the `IOApp` as demonstrated in the docs: https://typelevel.org/cats-effect/docs/getting-started

**Comment by Euse** [comment]
Thanks for the explanation! I'm going to close the issue then!
