### ISSUE TITLE
Should bracket emit Canceled(None) on OptionT and EitherT?

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#244]
Currently bracket emits `Completed` when we've got a `None` in `OptionT`. This may not be accurate.

One argument flying around is that OptionT basically does a form of interruption, None effectively interrupting a bind chain. So maybe we should emit `Canceled(None)` in such cases.

/cc @LukaJCB I don't remember what issues we had with `Error(None)`, which was in your initial design.

**Comment by oleg-py** [comment]
I think it should be doing the same thing as we do with EitherT, `Option[A]` being basically an `Either[Unit, A]`.

With this line of thinking we get `Canceled(None)` on `Left(_)` case - note that we cannot actually use error from Left, since `ExitCase` requires `Error[E]` and `Canceled[E]` to be the same `E`, and for `Sync` that is `Throwable`. This feels like an odd something to me.

**Comment by alexandru** [comment]
> I think it should be doing the same thing as we do with EitherT, Option[A] being basically an Either[Unit, A].

Both are doing the same thing already — currently they emit `Completed`. Note that the name `Completed` was chosen specifically to not mean `Success`, what it means basically is "not an error in this MonadError instance".

> note that we cannot actually use error from Left, since ExitCase requires Error[E] and Canceled[E] to be the same E

Right, but you can't design it in any other way.  You can say that `L` from `EitherT` is an error of some sort, but you're talking about a different `MonadError` instance. And what you have with EitherT doesn't necessarily match what you'll get with other monad transformers. Losing information is inevitable.

**Comment by oleg-py** [comment]
> Both are doing the same thing already — currently they emit `Completed` 

Yep, that's fine by me. I'm just saying the change should be consistent.

---

Another concern is `uncancelable`. Right now the intuition is that when you make something `uncancelable`, `Canceled` case will never be hit. This would no longer be true with such change, since you cannot replace `None` with `Some(_)` for arbitrary type.

**Comment by alexandru** [comment]
You’re right, was asking as a asking as a last opportunity for change, but haven’t encountered a case where I’d want this.

**Comment by durban** [comment]
I think it should return something which is not `Completed`. Because that would make it possible to define a more capable version of bracket:
```
sealed trait ExitCase[+E, +A]
case class Completed[A](a: A) extends ExitCase[Nothing, A]
// ... others as currently

def bracketCase[A, B](acquire: F[A])(use: A => F[B])(
  release: (A, ExitCase[E, B]) => F[Unit]
): F[B]
```
Which means that `release` can use the _result_ of `use` (if `use` is not failed/cancelled).
(Recently I found myself wanting to use this version of `bracket`.)

**Comment by alexandru** [comment]
@durban we can’t have `B` in `release` because it makes it less generic and harder to implement. In particular `Bracket` can be implemented by streaming abstractions and by introducing `B` in `release` that would no longer be possible.

We already discussed this in the original PR.

**Comment by alexandru** [comment]
I've analyzed the implementation again and we basically can't do it, the current implementation being fine as it is.

Closing the issue.

**Comment by LukaJCB** [comment]
The only way to do something different will also disallow streaming types, if we want to think about changing bracket, we'd need to first discuss if we want streaming types to be `Sync`s 👍
