### ISSUE TITLE
`race` behaves differently in CE2 vs. CE3?

### ISSUE THREAD

**Issue by LLCampos** [typelevel/cats-effect#2563]
```scala
import cats.effect.IO

import scala.concurrent.duration._
import cats.effect.unsafe.implicits.global

import java.util.concurrent.LinkedBlockingQueue

object LinkedBlockingQueueIssues extends App {
  val queue: LinkedBlockingQueue[Int] = new LinkedBlockingQueue[Int]()

  IO.race(IO.sleep(100.millis), IO.delay(queue.take())).unsafeRunSync()
}
```

The above, using CE 3.2.9, hangs.

But I would expect it to finish, as is does in the 2.5.4 equivalent:

```scala
package experiments

import cats.effect.{ContextShift, IO, Timer}

import scala.concurrent.duration._
import scala.concurrent.ExecutionContext.global
import java.util.concurrent.LinkedBlockingQueue
import scala.concurrent.ExecutionContext

object LinkedBlockingQueueIssues extends App {

  implicit val ec: ExecutionContext = global
  implicit val timer: Timer[IO] = IO.timer(global)
  implicit val cs: ContextShift[IO] = IO.contextShift(global)

  val queue: LinkedBlockingQueue[Int] = new LinkedBlockingQueue[Int]()

  IO.race(IO.sleep(100.millis), IO.delay(queue.take())).unsafeRunSync()
}

**Comment by vasilmkd** [comment]
Can you try `IO.interruptible(many = false)(queue.take())` in CE3?

This is a blocking queue and `take` can be interrupted, but we do not attempt it for `IO.delay` as it is a pretty expensive operation to do, and it is done the way it is for optimization purposes.

**Comment by LLCampos** [comment]
Ok, that works! Should a comment regarding differences in `.race` behavior be documented in the [Migration Guide](https://typelevel.org/cats-effect/docs/migration-guide)?

**Comment by vasilmkd** [comment]
The behavior of race has not changed. Cancelation is attempted, it's just that `queue.take` is not cancelable, it is _interruptible_ (by using `Thread.interrupt`, because `LinkedBlockingQueue` is a Java API). To do this, we have to set up a second fiber, to observe cancelation, run it in parallel, trigger interruption of a worker thread on our runtime, observe the interruption, recover from it and clean up. As you can see, we don't want this for every `IO.delay`.

The `many` parameter tells the implementation if it can attempt to interrupt the action many times or just once. We actually have a slightly tweaked syntax coming in `3.3.0` which will be out very soon. The new methods will be `IO.interruptible(thunk)` and `IO.interruptibleMany(thunk)`. We'll be sure to add scaladocs.
