### ISSUE TITLE
`forceR` success behavior ?

### ISSUE THREAD

**Issue by ronanM** [typelevel/cats-effect#2697]
Why success behavior of `a !> b` is different from `a *> b` ?

```scala
import cats.data.WriterT
import cats.syntax.all._
import cats.effect.implicits._
import cats.effect.unsafe.implicits.global
import cats.effect.IO
import scala.concurrent.duration.DurationInt

type Fx[A] = WriterT[IO, List[String], A]

def mk(i: Int): Fx[Int] =
  WriterT.liftF[IO, List[String], Int](IO.sleep(10.millis) *> IO.println(s"  Println: $i").as(i)).tell(List(s"Int:$i"))

val one: Fx[Int] = mk(1)
val two: Fx[Int] = mk(2)

val prg1 = one *> two
prg1.run.unsafeRunSync()
//  Println: 1
//  Println: 2
// res0: (List[String], Int) = (List(Int:1, Int:2),2)

val prg2 = one >> two
prg2.run.unsafeRunSync()
//  Println: 1
//  Println: 2
// res1: (List[String], Int) = (List(Int:1, Int:2),2)

val prg3 = one >>= (_ => two)
prg3.run.unsafeRunSync()
//  Println: 1
//  Println: 2
// res2: (List[String], Int) = (List(Int:1, Int:2),2)

val prg4 = one !> two
prg4.run.unsafeRunSync()
//  Println: 1
//  Println: 2
// res3: (List[String], Int) = (List(Int:2),2) <----------------------
```

**Comment by vasilmkd** [comment]
This is not unique to `WriterT`, something similar should also be happening with `StateT`. @djspiewak Can we do anything? I'm not sure if there's any room for improvement here.

**Comment by armanbilge** [comment]
The implementation of `forceR` for `WriterT` is given here:
https://github.com/typelevel/cats-effect/blob/c73512576734177d477bf0530910b56d72da3ed0/kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala#L794-L797

Which does discard completely the result of the left `WriterT`.

Assuming that `forceR` is a "primitive" of `MonadCancel` (i.e., an abstract member because the implementation cannot in general be expressed in terms of other methods), then IIUC the implementation for `WriterT` has to be in terms of the underlying effect's `forceR`. In which case, I don't think it's possible to change this.

I also don't see any laws expressing that `forceR` should be equivalent to `productR` in the happy-path.
https://github.com/typelevel/cats-effect/blob/series/3.x/laws/shared/src/main/scala/cats/effect/laws/MonadCancelLaws.scala

**Comment by ronanM** [comment]
Naively I thought that `a !> b` <=> `a.attempt *> b`, but it's definitively not the case.

This operator may need more documentation/:warning:warnings:warning:.

**Comment by djspiewak** [comment]
It absolutely needs more documentation. The discard of the left context is intentional, but it's certainly a bit weird. There was some really arcane reason why this had to be the case which escapes me at present, but iirc if you change it the laws will start failing.

**Comment by ronanM** [comment]
`ignoreLeft`/`discardLeft` may be more informative ?

**Comment by armanbilge** [comment]
I think it's worth noting that this problem of lost side-effects is specific to the `WriterT` monad transformer (and `StateT` as Vasil points out). The side-effect of "writing" is abstracted in Cats MTL as [`Tell`](https://typelevel.org/cats-mtl/mtl-classes/tell.html) (and state as [`Stateful`](https://typelevel.org/cats-mtl/mtl-classes/stateful.html)) which I believe you should be able to implement directly in terms of `IO` via an `IOLocal`. In that case, `forceR` _would_ preserve the side-effects of writing on the left side.

So, IMO, the problem here is not with `forceR` per se, but with providing an instance of `MonadCancel` for `WriterT`: even though it follows the `MonadCancel` laws, I'm not sure if it is a "lawful writer" (waves hands)—at the very least, it is a non-intuitive one anyway.

**Comment by ronanM** [comment]
On my project, my _"stack"_ is `Fx[_]` defined like this :
```scala
type CIO[A] = IorT[IO, LogTree, A]
type Fx[A]  = Kleisli[CIO, MyEnv, A]
```
And I use Cats MTL `Chronicle[CIO, LogTree]` to have a tree-like _"logging"_ accumulating informations about nested executions of functions (message, result, timings, user informations, etc.).

With my `Fx[_]`, the `forceR` behaviour is not obvious.
