### ISSUE TITLE
NonDaemonThreadLogger and SBT 1.6.x

### ISSUE THREAD

**Issue by mattroberts297** [typelevel/cats-effect#2745]
Using SBT 1.6.x the `NonDaemonThreadLogger` appears to print out SBT-related threads. Reproducible:

Main.scala
```scala
import cats.effect.{ExitCode, IO, IOApp}

object Main extends IOApp {
  def run(args: List[String]): IO[ExitCode] = {
    IO(ExitCode.Success)
  }
}
```

build.sbt
```scala
ThisBuild / scalaVersion     := "2.13.7"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

lazy val root = (project in file("."))
  .settings(
    name := "sbt-cats-repro",
    libraryDependencies ++= Seq(
      "org.typelevel" %% "cats-effect" % "3.3.4"
    )
  )
```

project/build.properties
```ini
sbt.version=1.6.1
```

Output:

```
sbt:sbt-cats-repro> run
[info] running Main
[success] Total time: 1 s, completed 11-Jan-2022 16:44:22
sbt:sbt-cats-repro> Non-daemon threads currently preventing JVM termination: - 175: Thread[com.swoval.files.apple.FileEventsMonitor.runloop,5,main]
 -  - 23: Thread[pool-1-thread-4,5,main]
 -  - 180: Thread[sbt-socket-server,5,main]
 -  - 173: Thread[com.swoval.files.SymlinkWather.callback-executor-1,5,main]
 -  - 181: Thread[com.swoval.files.apple.FileEventsMonitor.callback-1,5,main]
 -  - 22: Thread[pool-1-thread-3,5,main]
 -  - 177: Thread[com.swoval.files.SymlinkWather.callback-executor-1,5,main]
 -  - 176: Thread[com.swoval.files.apple.FileEventsMonitor.runloop,5,main]
 -  - 179: Thread[com.swoval.files.apple.FileEventsMonitor.runloop,5,main]
 -  - 178: Thread[FileTreeRepository-callback-executor-1,5,main]
 -  - 29: Thread[sbt-console-input-reader,5,main]
 -  - 1: Thread[main,5,main]
 -  - 21: Thread[pool-1-thread-2,5,main]
 -  - 19: Thread[pool-1-thread-1,5,main]
 -  - 172: Thread[com.swoval.files.apple.FileEventsMonitor.runloop,5,main]
 -  - 174: Thread[FileTreeRepository-callback-executor-1,5,main]
 -  - 24: Thread[pool-1-thread-5,5,main]
 -  - 193: Thread[com.swoval.files.apple.FileEventsMonitor.callback-1,5,main]
```

I suspect this issue is now observable due to this SBT change: https://github.com/sbt/sbt/pull/6665. Though when I attached a debugger to SBT 1.5.x I observed that the `NonDaemonThreadLogger` is terminated before it gets to `detectThreads()`, so perhaps this has always been an issue, but just not observable.

**Comment by djspiewak** [comment]
Yeah I think this has always been an issue, just not observable. The `NonDaemonThreadLogger` shouldn't be run in an unforked sbt `run`. It just doesn't have any meaning in that context, *and* it's not useful anyway because sbt's thread cleaner will take a wrecking ball to all of that anyway. Seeing as we now have the ability to detect this scenario, we just shouldn't run the logger in that case.

Quick workaround while we get to a fix: `run / fork := true`. This will also fix *other* issues since unforked runs really don't work very well in sbt anymore (e.g. <kbd>ctrl</kbd>-<kbd>c</kbd> works perfectly in Cats Effect in every case *except* unforked sbt, simply because unforked sbt has an unresolved bug which prevents it from forwarding the interrupt).

**Comment by mattroberts297** [comment]
Thank you @djspiewak and @vasilmkd 🙇‍♂️
