### ISSUE TITLE
Special-case more specific runtime types in derived typeclasses

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2772]
In each of the derived typeclasses (e.g. `Concurrent` for `EitherT`), we should `match` on the runtime type of the `F` constraint and try to provide the more specific runtime type if at all possible (e.g. if the `F` constraint is `Async` and not `Concurrent`, then we should instantiate an `Async` for `EitherT` and return *that*, preserving the runtime specificity). This is needed to ensure that #2771 is fairly robust.

**Comment by ybasket** [comment]
I had a look into this and before going through all files, I wanted to ensure I got things right. This runtime `match` is to be done for every type class that's a subtype of the one we're asked to derive, right? So `Async` & `Temporal` when deriving `Concurrent` (obviously only for monad transformers that can implement the stronger type class at all)? Asking because #2771 mentions only `Async` as motivation and we impose a runtime penalty here, so I'd try to keep it as low as possible while covering all actual use cases (is there one for `Temporal`?). Example of what I aim at so far:

```scala
  implicit def genConcurrentForOptionT[F[_], E](
      implicit F0: GenConcurrent[F, E]): GenConcurrent[OptionT[F, *], E] = F0 match {
    case async: Async[F @unchecked] =>
      Async.asyncForOptionT(async)
    case temporal: GenTemporal[F @unchecked, E @unchecked] => // is this one really needed?
      GenTemporal.genTemporalForOptionT(temporal)
    case concurrent =>
      new OptionTGenConcurrent[F, E] {
        override implicit protected def F: GenConcurrent[F, E] = concurrent
      }
  }
```

**Comment by djspiewak** [comment]
That's the pattern exactly! Really sucks, tbh, because it bloats up the boilerplate quite a lot, but the results are really nice. Also I would most definitely keep the `GenTemporal` case, just for consistency, though I can't think of a scenario where we would leverage it (at least for the moment).
