### ISSUE TITLE
Proposal: Delete IO#ensuring

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3]
It's a really useful function, but it suffers from two problems:

- The name is identical to `Predef.ensuring` and very very close to `MonadError#ensure`, but the functionality is completely different
- The functionality really belongs on `MonadError` in a generic capacity

Seems like it would be better just to pull it back, get it off of `IO`, and propose a similar function (likely with a different name) to cats.

**Comment by alexandru** [comment]
If the intent is to keep `IO` minimal, delegating its functionality to Cats' type-classes, then yes, it makes sense to push that into `MonadError`.

**Comment by rossabaker** [comment]
At the risk of widening this discussion, I'd like to come to a consensus on "keep `IO` minimal and teach everyone to `import cats.implicits._`" vs. "make a more discoverable `IO` and be sad about the redundancies."

**Comment by alexandru** [comment]
I think that `import cats.implicits._` is fine, because this is meant to be deeply integrated into and piggyback on Cats.

I'm a little selfish, but the reason for why I want this is because I feel that Cats has missing type-classes, or type-classes with incorrectly used operations and pushing more responsability on Cats' type-classes will make Cats-core better.

For example I discovered that `ApplicativeError.catchNonFatal` is not being overridden for type-classes that might implement it lazily, like in `cats.Eval`, making it next to useless, even though it is being promoted as a lazy `Applicative.pure`.

**Comment by djspiewak** [comment]
Alright, I'll PR `ensuring` (probably under some other name) to `ApplicativeError` in cats-core.  Once that's in, I'll remove it here.

On the broader topic of discoverability vs implicits…  I think that's a dichotomy that we should really figure out how to solve in the tooling layer, and trying to contort our implementations to resolve it seems… incorrect.  So whenever it makes sense, removing stuff from `IO` and letting the typelcasses do the heavy lifting should be our policy.  The exceptions should be primarily in the areas of efficiency (i.e. where we can get a better-than-default implementation by specializing).  If we specialize a function, we can just put it concretely on `IO` and delegate from the typeclass instance.
