### ISSUE TITLE
Update documentation or add an FAQ entry to note changes in the way that blocking tasks are executed

### ISSUE THREAD

**Issue by DavidGregory084** [typelevel/cats-effect#3005]
I don't think that there is an existing issue for this, please close if there is!

Folks on Discord frequently ask why their tasks are not running on the blocking pool, e.g.

> In cats effect 3 there are an operator blocking defined on the IO and it can be used as:
> ```object Main extends IOApp.Simple {
>
>  override def run(): IO[Unit] =
>    IO(println(Thread.currentThread().getName)) >> IO.blocking {
>      println(Thread.currentThread().getName)
>    } >> IO(println(Thread.currentThread().getName))
>
>}
>```
>
>The output when I run this is something like:
>io-compute-8
>io-compute-8
>io-compute-8
>
>Which I interpret to that the computer-based execution context is used through out the program even though I have declared part of the program as blocking.
>
> According to the docs the following behaviour is to be expected:
>`IO.println("current pool") >> IO.blocking(println("blocking pool")) >> IO.println("current pool")`
>
>So I had expected the second effect to be executed on the blocking pool? I’m clearly missing something here.

Perhaps the [existing documentation](https://typelevel.org/cats-effect/docs/thread-model#blocking) should be updated or perhaps we should add an FAQ entry to document that `IO.blocking` does not necessarily shift tasks onto the blocking pool anymore as of [3.3.2](https://github.com/typelevel/cats-effect/releases/tag/v3.3.2).

**Comment by djspiewak** [comment]
Agreed! We really should update the documentation on this.

**Comment by DavidGregory084** [comment]
I think the confusing thing is that it's not immediately apparent that the behaviour of `IO.blocking` has changed unless you read this part of the 3.3.2 release notes very carefully:

> These improvements, taken together, mean that scala.concurrent.blocking inside of delay is actually faster than the IO.blocking operation by a significant margin, meaning that we can reap immediate performance benefits by converting IO.blocking and IO.interruptible to use this native mechanism rather than an ancillary thread pool.

I presume that this means that `IO.blocking` and `IO.interruptible` have indeed been updated to receive these perfomance benefits. 😛 Is there an up-to-date summary of the new model somewhere? When is the blocking pool still used?

> In this release, Vasil has changed the behavior of the pool to seamlessly shift worker state when a blocking section is hit, effectively morphing another thread into the exact state as the now-blocked thread. 

What does this mean? Is this "morphed thread" a new compute pool thread created to resume after the blocking section? Or is it how a compute pool thread becomes a blocking thread temporarily? If so, what happens to the compute pool threads that morph into blocking threads? Are they replaced by a new compute pool thread that is created when a blocking section is hit similar to the default EC? Is this what the caching of "spare threads constructed when blocking operations are hit" refers to? Or do they change back into compute pool threads once the blocking section is complete?

Trying to speedrun asking as many stupid questions as it takes to understand what we need to change here 😆

**Comment by vasilmkd** [comment]
Sorry for being away for some time.

The `blocking` pool exists in all runtimes, as a backup option. If you don't use the default runtime, or create a runtime with a custom (meaning, it is not an instance of `cats.effect.unsafe.WorkStealingThreadPool`) `compute` thread pool, then all `IO.blocking`, `IO.interruptible` and `IO.interruptibleMany` calls incur a switch to and from the `blocking` pool.

If the `compute` pool is an instance of `cats.effect.unsafe.WorkStealingThreadPool`, then there are some optimizations that are applied.

The `WorkStealingThreadPool` implements the `scala.concurrent.BlockContext` trait, which allows it to intercept and prepare for `scala.concurrent.blocking` regions.

When this interception code is executed, it polls the status of the compute thread pool and decides whether it needs to start new threads in preparation of blocking _or_ if there are _cached_ threads that can jump in and replace the current thread that is about to block.

For example, if the compute pool has 4 compute threads, and one is about to execute a `scala.concurrent.blocking` thunk, the thread pool will get a replacement thread (new or cached) and have 5 threads (1 of which is blocked and 4 are compute threads). This is conceptually the same as shifting the computation to the blocking thread pool and continuing with the original 4 compute threads. The blocking pool may use a cached thread if it has any, or spawn a new one if necessary to run the blocking computation.

Continuing. As soon as the replacement thread is found (new or cached), an internal transfer of data structures takes place between the current thread that is about to be blocked and the replacement thread. Thus, from the outside (and even to the other threads inside the compute pool) the replacement thread _becomes_ the current thread. This is completely opaque to the world.

As soon as this data structure takes place, the thread that is about to block goes ahead and executes the blocking code, which may launch rockets. At this point, the thread running that code is _no longer_ a part of the compute pool, it's just a background thread.

At the same time, the replacement thread that became the original thread is now a blessed compute thread and can execute fibers (in fact it inherits the complete state of the blocked thread, including all fibers and whatever data structures are necessary for bookkeeping and execution). This thread, along with all other compute threads now constitutes the compute pool.

As a final detail, when the blocked thread is done with the execution of the blocking code (the rockets were launched), it instructs the blocking fiber that it doesn't belong to the compute pool anymore. The fiber enqueues itself on the compute pool, as any other fiber. The thread enqueues itself on the queue of _cached_ threads of the pool, to be used for other blocking execution in the future, without paying the price for spawning a thread. The thread is now suspended so that it _doesn't_ fight the compute threads for CPU time and the compute pool continues with the configured number of threads from then on.

Finally, `IO.blocking`, `IO.interruptible` and `IO.interruptibleMany` have logic to discriminate based on the runtime compute pool. If they cannot determine that they are running on an instance of `cats.effect.unsafe.WorkStealingThreadPool` (for example, when using a user supplied custom compute pool, or when running `evalOn`), they fall back to the `blocking` pool. If they are indeed running on our runtime, then all three calls are opaquely rewritten to `IO.apply(scala.concurrent.blocking(thunk))` and executed.

(I might be blanking on some minute details about `IO.interruptibleMany`, I don't remember exactly, we can double check. `IO.blocking` is definitely rewritten as I explained).

Hope this is useful.

**Comment by DavidGregory084** [comment]
This is incredible detail, thanks so much for this @vasilmkd!

**Comment by martinprobson** [comment]
I have raised a PR to add the new blocking behaviour to the faq section that also links [comprehensive detail](https://github.com/typelevel/cats-effect/issues/3005#issuecomment-1134974318)  above
