### ISSUE TITLE
Change thread name when it becomes a "blocker"

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3010]
Simple thing, but when a thread transmutes into a blocking agent, we should change its name from `io-compute` to `io-blocker` or something like that. This seems to come up a lot in Discord and it's not a difficult solve. :-)

**Comment by djspiewak** [comment]
This requires a bit of introspection of the WSTP, but it's not that crazy and @vasilmkd has written us all a novella in the comments.

**Comment by vasilmkd** [comment]
Should be limited to `WorkerThread.scala`, off the top of my head, the name should be set to "blocker" in `blockOn`. It can probably be reset to "compute" in the method that transfers data structures, probably called `init` something.

**Comment by aeons** [comment]
I took a quick look at this, but I'm stuck on getting a test in place that can check that the thread name gets reset correctly. How can I force a thread out of "blocking mode"?

**Comment by djspiewak** [comment]
> How can I force a thread out of "blocking mode"?

You mean for something like this? `IO.blocking(()) *> IO(Thread.currentThread().getName())`? I *think* if you toss an `IO.cede` between those two, it'll kick things back into compute.

**Comment by armanbilge** [comment]
Won't that just move the fiber back into compute? But it won't make the thread back into a compute thread.

In fact, I'm a bit fuzzy on when/if exactly that happens. If blocking threads do indeed sometimes become compute threads, it would only be because another compute thread has itself become a blocking thread. So seems that would be the way to trigger it.

**Comment by djspiewak** [comment]
> Won't that just move the fiber back into compute? But it won't make the thread back into a compute thread.

I think it forces the fiber back onto a compute thread. I don't believe that threads can ever transmute back into compute agents, but I'm not 100% sure of this.

**Comment by vasilmkd** [comment]
It does move the fiber back to a compute thread (it works as if scheduled externally, because the blocking thread is no longer a part of the compute pool).

Cached threads are threads that blocked at some time in the past, but can become compute threads again, instead of spawning a new thread.

All of this is because of the signature of `blockOn` which forces you to run the blocking code synchronously, the only thing you can do in advance is write your will (spawn or obtain a cached thread to replace you).

**Comment by aeons** [comment]
The `cede` was enough to kick it back to a compute thread.
