### ISSUE TITLE
IO.blocking doesn't run on a io-blocking thread

### ISSUE THREAD

**Issue by don41382** [typelevel/cats-effect#3083]
I have a simple cats app, which calls `IO.blocking` for a blocking task. When I inspect it with visualvm, I see that it is actually running on a `io-compute-x`. Am I missing something? Should it be on a thread named `io-blocking-x`:

```
import cats.effect.{IO, IOApp}

object Main extends IOApp.Simple {

  def blockingDemo: IO[Unit] = IO.blocking {
    println("waiting ...")
    Thread.sleep(10000)
    println("done!")
  }

  override def run: IO[Unit] =
    blockingDemo
}
```

I am using Cats-Effect 3.3.12

**Comment by armanbilge** [comment]
Yes, this is expected due to an optimization. See this FAQ (unfortunately it got merged to the wrong branch so is not live on the website 😕 ).
https://github.com/typelevel/cats-effect/blob/e618a7760130b73783e9223ac4951ef15fe08472/docs/faq.md#blocking-behaviour

Although note that as of 3.3.13 the name should change thanks to this PR:
- https://github.com/typelevel/cats-effect/pull/3012

**Comment by don41382** [comment]
Thanks for the fast response. And yes, the `io-compute` was strangely behaving like a blocking one.  Now I know why ...

But having different names makes debugging much easier. Let's wait for 3.3.13 :-)

**Comment by armanbilge** [comment]
@don41382 https://github.com/typelevel/cats-effect/releases/tag/v3.3.13 😉
