### ISSUE TITLE
Tracing for Scala Native

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3167]
Like, serious bounty for whoever figures this out 😛 cause I'm getting hella annoyed trying to debug stack traces like this:

```
java.io.IOException: -97
    at java.lang.StackTrace$.currentStackTrace(Unknown Source)
    at java.lang.Throwable.fillInStackTrace(Unknown Source)
    at fs2.io.uring.Uring$$anon$1.$anonfun$apply$8(Unknown Source)
    at fs2.io.uring.Uring$$anon$1$$Lambda$4.apply(Unknown Source)
    at cats.ApplicativeError.$anonfun$raiseWhen$1(Unknown Source)
    ...
```

The lack of line numbers hurts too, but Anton is already working on that with his LSPs 💪 

In all honesty I have not really investigated this. The important pieces are:
1. Some strategy for uniquely identifying lambdas. On the JVM we use its class, on JS its source code. It is fully possible we could use the class on Native too, I am not sure how they are represented in the runtime. Figuring this out is the most important thing.
2. Some data structure for caching traces. The JVM uses [`ClassValue`](https://docs.oracle.com/javase/8/docs/api/java/lang/ClassValue.html) which is currently not available on Native. I do not know if that's a fundamental limitation or just that nobody has bothered to implement it. Also a vanilla map may work perfectly fine here: unlike the JVM I do not think there is a notion of lazy class loading/unloading at runtime.
3. Filtering stack traces. Good luck with that 😇 this isn't hard so much as it is annoying. For Scala Native it is complicated by the fact there are a hundred-and-one runtimes out in the wild.

In fact, if we figure out tracing, I'm pretty sure we will get fiber dumps for free since all that machinery is already in place. Edit: except for the signal handlers, lol.

**Comment by djspiewak** [comment]
Poking @WojciechMazur for async thoughts.

**Comment by WojciechMazur** [comment]
> 1. It is fully possible we could use the class on Native too, I am not sure how they are represented in the runtime.

In most cases, lambdas are represented as an anonymous class, however, their naming is stable only within a single compilation unit - changing the order of their definition changes their name (within Scala compiler). 

Example of invocation in nir: 
```
// allocate lambda
 %8 = classalloc @"T15Test$$$Lambda$2"
 
 // call its constructor (pass explicit and implicit arguments (also closure environment)
 %9 = call[(@"T15Test$$$Lambda$2", @"T5Test$", @"T21java.lang.ThreadLocal", @"T41java.util.concurrent.atomic.AtomicInteger", int) => unit] @"M15Test$$$Lambda$2RL5Test$L21java.lang.ThreadLocalL41java.util.concurrent.atomic.AtomicIntegeriE" : ptr(%8 : !?@"T15Test$$$Lambda$2", %1 : @"T5Test$", %2 : @"T21java.lang.ThreadLocal", %3 : @"T41java.util.concurrent.atomic.AtomicInteger", %5 : int)
 
 // resolve virtual method to call 
 %10 = method %7 : !?@"T24scala.concurrent.Future$", "D5applyL15scala.Function0L33scala.concurrent.ExecutionContextL23scala.concurrent.FutureEO"
 
 // pass the lambda as scala.Function0
 %11 = call[(@"T24scala.concurrent.Future$", @"T15scala.Function0", @"T33scala.concurrent.ExecutionContext") => @"T23scala.concurrent.Future"] %10 : ptr(%7 : !?@"T24scala.concurrent.Future$", %8 : !?@"T15Test$$$Lambda$2", %4 : @"T33scala.concurrent.ExecutionContext")
```
In general for gathering positions we use [libunwind](https://www.nongnu.org/libunwind/). It traverses the call chain of the current thread and allows us to get the [name of current function](https://www.nongnu.org/libunwind/man/unw_get_proc_name(3).html). It also has an API for [gathering function info](https://www.nongnu.org/libunwind/man/unw_get_proc_info(3).html) but currently it's not used. I have no idea if we can populate this info structure with information about the source position. 

However, depending on the libunwind is not guaranteed to always contain the full callback. For example, the function might be completely inlined and we would lose that frame info. Maybe if we would have the debug symbols in Scala Native somehow we would be able to map the instructor pointer to the source location, but at this moment I cannot confirm that. 

What's important from the point of multithreading libunwind only can operate on the current thread. If we would like to gather info from other threads then we need to introduce some kind of asynchronous communication, eg. I've used a working prototype based on signals handling, but it's not stable. 

At this point, we get to point 3. manipulating stack trace. In general info we get from libunwind is just a plain c-string containing the mangled name of a function. This mangled name needs to be parsed so we can extract info about class and method name. In general, on most runtimes, it should work similarly but might differ in some prefixes or suffixes.

I'm not aware of how fibers are exactly executed, but I guess that context switching between fibers might lead to some kind of malformation of traces in terms of libunwind usage.  In general idea of data structure tightly coupled to fiber instance might be a good solution, however, it probably should only store references to frames, instead of the whole stack trace element - because parsing it is expensive.

**Comment by armanbilge** [comment]
Thanks for that! I will have to digest that a bit.

> In general for gathering positions we use [libunwind](https://www.nongnu.org/libunwind/). It traverses the call chain of the current thread and allows us to get the [name of current function](https://www.nongnu.org/libunwind/man/unw_get_proc_name(3).html). It also has an API for [gathering function info](https://www.nongnu.org/libunwind/man/unw_get_proc_info(3).html) but currently it's not used.

This sounds really interesting. If we can get the information we want without having to create an entire stack trace then that will be a big win for performance I think.

**Comment by djspiewak** [comment]
This does all sound promising, though just to reiterate quickly so we don't get lost in the details of *how* we implemented this on the JVM, what we need are two things:

- The ability to get the source information for the caller of the current function
- The ability to *very efficiently* introspect a function value into a cache key such that all closures instantiated from that same lambda will share the same identity
