### ISSUE TITLE
`uncancellable` test fails

### ISSUE THREAD

**Issue by SystemFw** [typelevel/cats-effect#332]
This test fails, you can see it when #331 is merged

```scala
      val received =
        for {
          f <- (fa <* IO.cancelBoundary).uncancelable.start
          _ <- f.cancel
          a <- f.join
        } yield a

      received <-> fa
```

**Comment by alexandru** [comment]
Makes sense. The problem is that `start` doesn't necessarily have a chance to execute the source under the new cancelation model. So it doesn't matter if the source is `uncancelable` because it was never evaluated.

Fixing it basically involves usage of a latch.

But I think we already have a law that tests `uncancelable`, don't we?
If we do, then we can just drop the test.

**Comment by SystemFw** [comment]
> he problem is that start doesn't necessarily have a chance to execute the source under the new cancelation model. So it doesn't matter if the source is uncancelable because it was never evaluated.


All makes sense. I'll double check and raise a PR one way or another. Probably easier (git wise) if the tests PR gets merged first

**Comment by SystemFw** [comment]
Changed my mind, I can probably tackle the failing test in the PR that's already there
