### ISSUE TITLE
Why is computation running on the blocking pool?

### ISSUE THREAD

**Issue by don41382** [typelevel/cats-effect#3395]
I am currently using `cats-effects 3.4.5` and I have strange behavior. I am not sure, if this is a bug or if it works like designed.

My CPU intensive computation runs on the `io-compute-blocker`threads and not on the  `io-compute` threads, when I first do IO and than the computation. If I switch it around, it seems to work. Any idea why?

Thread pool correctly used (first cpu, than IO):
```
import cats.effect.{ExitCode, IO, IOApp}

object SimpleIODemo extends IOApp {

  def cpu(): IO[Unit] = IO {
    println(s"${Thread.currentThread().getName}: cpu")
    (1 to 5000000).foreach(n => Math.tan(n))
  }

  def blocking(): IO[Unit] = IO.blocking {
    println(s"${Thread.currentThread().getName}: blocking")
    Thread.sleep(2000)
  }

  override def run(args: List[String]): IO[ExitCode] = for {
    _ <- cpu()
    _ <- blocking()
  } yield ExitCode.Success
}
````

Output:
```
io-compute-1: cpu
io-compute-blocker-1: blocking
```

When I just switch the order. First do the blocking and than the cpu intensive operation, cats io seems to use the wrong thread pool
```
...
  override def run(args: List[String]): IO[ExitCode] = for {
    _ <- blocking()
    _ <- cpu()
  } yield ExitCode.Success
...
```

Output:
```
io-compute-blocker-3: blocking
io-compute-blocker-3: cpu
```

How does this happen? Am I doing something wrong?

**Comment by don41382** [comment]
If I put the IO into a fiber it works correctly:
```
...
  def run = for {
    _ <- cpu()
    _ <- blocking()
  } yield ()

  override def run(args: List[String]): IO[ExitCode] = for {
    fiber <- run.start
    _ <- fiber.join
  } yield ExitCode.Success
...
´´´

Output:
```
io-compute-1: cpu
io-compute-blocker-1: blocking
```

**Comment by durban** [comment]
This is normal: https://typelevel.org/cats-effect/docs/faq#why-is-my-io-running-on-a-blocking-thread

**Comment by don41382** [comment]
Thanks @durban. I didn't know about this optimization, but I think the ForkJoinPool behaves the same way.

Anyways, isn't this dangerous? I thought the goal of having a `io-compute` is to limit the threads to the amount of CPU's. But if waiting IO is done beforehand, the guarantee is broken. Right?

For example my system has 8 cores and the `cpu` intensive operation should not exceed this limit. But sadly it runs the computation on 16 threads:

```
  def run = for {
    _ <- blocking()
    _ <- cpu()
  } yield ()

  override def run(args: List[String]): IO[ExitCode] = for {
    _ <- (1 to Runtime.getRuntime.availableProcessors() * 2)
      .map(_ => run)
      .toList
      .parSequence
```

Output:
```
io-compute-blocker-7: blocking
io-compute-blocker-11: blocking
io-compute-blocker-9: blocking
io-compute-blocker-10: blocking
io-compute-blocker-1: blocking
io-compute-blocker-3: blocking
io-compute-blocker-4: blocking
io-compute-blocker-15: blocking
io-compute-blocker-2: blocking
io-compute-blocker-12: blocking
io-compute-blocker-5: blocking
io-compute-blocker-6: blocking
io-compute-blocker-8: blocking
io-compute-blocker-21: blocking
io-compute-blocker-14: blocking
io-compute-blocker-13: blocking
io-compute-blocker-11: cpu
io-compute-blocker-10: cpu
io-compute-blocker-9: cpu
io-compute-blocker-7: cpu
io-compute-blocker-1: cpu
io-compute-blocker-15: cpu
io-compute-blocker-21: cpu
io-compute-blocker-2: cpu
io-compute-blocker-14: cpu
io-compute-blocker-13: cpu
io-compute-blocker-4: cpu
io-compute-blocker-6: cpu
io-compute-blocker-12: cpu
io-compute-blocker-8: cpu
io-compute-blocker-3: cpu
io-compute-blocker-5: cpu
```

Is this also the expected behavior?

VisualVM shows 16 threads running at the same time:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/1768764/216328389-b11efac0-1f69-4b74-af63-8f26d0ef29f9.png">

**Comment by durban** [comment]
I'm sure more knowledgeable people will correct me, but my current understanding is this: yes, this is expected with your code as it is.

Yes, due to this optimization, it is possible for a _short period of time_ that more threads are doing CPU heavy work than the size of the WSTP. (In general, it is impossible to make a `blocking` task _not_ use the CPU. I can even do `IO.blocking { while (true) {} }` if I want.) But this period of time it (usually) _very_ short.

In your case, it tooks much longer time to get back at the compute pool, because immediately after `blocking` there is an indivisible, long `IO.delay` (5 million `Math.tan`). This makes it hard (or impossible) for the Cats Effect scheduler to work optimally; it is generally assumed that indivisible tasks are short (except of course `blocking`). There are useful things written about this here: https://typelevel.org/cats-effect/docs/core/starvation-and-tuning#increase-granularity

Just to demonstrate the magnitude of time these things take (obviously not very good test, but it gives a general idea):

```scala
import cats.effect.{ IO, IOApp }

object Blocking extends IOApp.Simple {

  def run: IO[Unit] = {
    val t1 = IO.blocking { () }.flatMap { _ =>
      val check = IO { Thread.currentThread().getName().contains("blocker") }
      IO.println("Starting checks on " + Thread.currentThread().getName()).flatMap { _ =>
        IO.asyncForIO.timed(IO.asyncForIO.whileM_(check)(IO.unit)).flatMap {
          case (delta, _) =>
            IO { println(s"Back on the WSTP (after ${delta.toMillis}ms): " + Thread.currentThread().getName()) }
        }
      }
    }

    val t2 = IO.asyncForIO.timed(IO { (1 to 5000000).foreach(n => Math.tan(n.toDouble)) }).flatMap {
      case (delta, _) =>
        IO.println(s"Math took ${delta.toMillis}ms")
    }

    t1 *> t2
  }
}
```

For me this  prints:
```
Starting checks on io-compute-blocker-X
Back on the WSTP (after 3ms): io-compute-Y
Math took 305ms
```

So the indivisible task took about ×100 more time than getting back on the compute pool in the case of very granular tasks.

**Comment by don41382** [comment]
Thank you, Daniel, for the helpful example. May I repeat it in my own words to ensure that I have a clear understanding:

Due to the long blocking IO, it was impossible for the scheduler to switch to the `compute` pool.

After some testing, I figured out, that the reason might not be the long `blocking` or `cpu` duration (it actually doesn't matter how long both IO are), it's the gap between the IO's `blocking` and `cpu` Like your showed in your example. If I just add a `IO.sleep(0.milli)` in between, the shift happens:

```
  def run = for {
    _ <- blocking()
    _ <- IO.sleep(0.millis)
    _ <- cpu
  } yield ()
```

Output
```
io-compute-blocker-2: blocking (16x)
io-compute-21: cpu (16x)
```

I am still not sure, why this helps. I guess `IO.sleep` must call internally the context shifter.

**Comment by don41382** [comment]
Another downside, when `cpu` piggybacks `blocking` is that you won't get this beautiful warning message `"[WARNING] Your app's responsiveness to a new asynchronous event [...]"`. This would not show up in such cases, but would be super useful, if you would have CPU starvasion or running blocking IO in the wrong place.

**Comment by armanbilge** [comment]
> is that you won't get this beautiful warning message `"[WARNING] Your app's responsiveness to a new asynchronous event [...]"`

The good news is if you are not getting that warning, then you are not suffering from observable starvation :) (except in some extremely pathological scenarios).

That warning is _empirical_. That means it actually tests for starvation, at runtime, and reports it. It's not a theoretical/analytical test, so it won't have "holes" in its logic.

---

We get this question very frequently, which I why I added the linked FAQ. It would be great to know how we can improve it so that it can better answer similar questions in the future. Thanks!

https://typelevel.org/cats-effect/docs/faq#why-is-my-io-running-on-a-blocking-thread

**Comment by durban** [comment]
Yeah, as far as I know, it gets back at the WSTP when the next `async`/`cede` is encountered. Your `sleep` is basically an `async`. (Btw, instead of `sleep(0)` you can always do `cede`.) In my example, an "auto-cede" happens after some "steps" in the interpreter. So "after a short time it gets back at the WSTP" means "after a few steps". If the "steps" are uniformly short, this is indeed a short time. If there are very long "steps" (like your `delay`): it's still a few steps, but can be a long time. And you can immediately "force" getting back, with an `async` or an explicit `cede`, as you've discovered.

However, a very long `delay` on the WSTP can still be pretty bad, so if possible, it might be worth breaking it up a little (see the docs I've linked before).

**Comment by don41382** [comment]
I believe we can now resolve this issue. I now understand the optimization benefits of not assigning every CPU task to a `compute` thread.

Thank you @durban for taking the time to provide such thorough examples!
