### ISSUE TITLE
Add method to configure IO app before running it

### ISSUE THREAD

**Issue by omerlh** [typelevel/cats-effect#3687]
I am using [Ciris](https://cir.is/) for defining configuration and I would like to use it to configure some variables like `blockedThreadDetectionEnabled`, `cpuStarvationCheckInitialDelay` . The problem is - I can use Ciris values only inside `run` (it returns a resource) and `run` is called after `CpuStarvationCheck` is initialized (at least this is what I got from the code).

It would be nice to have a method like `configure` / `setup` that will be called before `run` on `IOApp.Simple` and can be used to configure global system parameters

**Comment by armanbilge** [comment]
> The problem is - I can use Ciris values only inside `run` (it returns a resource)

Can you use `SyncIO` with Ciris? In that case, you can use it to override these methods with your configuration.

https://github.com/typelevel/cats-effect/blob/e9aeb8ccb53016a37588256f4c8086f8ef1612bc/core/jvm/src/main/scala/cats/effect/IOApp.scala#L162-L166

https://github.com/typelevel/cats-effect/blob/e9aeb8ccb53016a37588256f4c8086f8ef1612bc/core/jvm/src/main/scala/cats/effect/IOApp.scala#L259-L260

Otherwise what you are asking is impossible: if Ciris returns an `IO` you need an `IORuntime` to run it. But to get an `IORuntime` then you need to decide these configurations.

**Comment by omerlh** [comment]
Ahh that's a fair point that I wasn't aware of - sorry for being noob! I will revert to using env vars directly in this case - thanks for the quick response!
