### ISSUE TITLE
`IOApp.reportFailure` is not invoked for a NonFatal exception 

### ISSUE THREAD

**Issue by kamilkloch** [typelevel/cats-effect#3768]
```scala
object ReportFailureApp extends IOApp.Simple {

  override protected def reportFailure(err: Throwable): IO[Unit] = IO.println(s"Failure")

  override def run: IO[Unit] = IO(throw new Exception(""))
}
```
prints stack trace instead of "Failure".

**Comment by armanbilge** [comment]
This is the correct and expected behavior.

https://github.com/typelevel/cats-effect/blob/25c948b065de0c7c77c9655162cdeb093f0b2b3b/core/jvm/src/main/scala/cats/effect/IOApp.scala#L235-L243

`reportFailure` is specifically for "unhandled" errors. An unhandled error is an error that is raised on a `Fiber` that nobody is `join`ing.

For example:

```scala
import scala.concurrent.duration._

override def run: IO[Unit] = IO(throw new Exception("")).start *> IO.sleep(1.second)
```

In this case, the exception is raised on a `Fiber` with no listeners. So nobody would be notified about that error. Therefore it is unhandled, and it goes through the `reportFailure` mechanism.

---

An error raised in `run` is considered to be "handled" because it is being raised directly to your application's main. If you want to handle errors that are raised in `run`, use `handleErrorWith` or similar.
