### ISSUE TITLE
Provide Parallel instance for Concurrent

### ISSUE THREAD

**Issue by scf37** [typelevel/cats-effect#450]
parMap/parSequence methods on collections require instance of `Parallel` which is not really convenient:

```scala
// for IO, G is IO.Par - implementation detail
def runInParallel[F[_]: Monad, G[_], A](list: List[F[A]])(implicit P: Parallel[F, G]): F[List[A]] = list.parSequence
```

But it seems that `Parallel[F, F[Fiber[F, ?]]` can be derived from `Concurrent[F[_]]` transforming above code to something like:

```scala

  type Fib[F[_], A] = F[Fiber[F, A]]
  implicit def parallelInstance[F[_]: Concurrent]: Parallel[F, Fib[F, ?]] = ???

  def runInParallel[F[_]: Concurrent, A](list: List[F[A]]): F[List[A]] = list.parSequence[Fib[F, ?]]
```

Here is some working PoC:
https://scastie.scala-lang.org/doJMQnN0SMqeYK2RafLAQg

**Comment by djspiewak** [comment]
Sorry for not getting to this sooner! This does indeed look interesting. The tricky bit is the implicit scoping. You *may* be able to get this to work by putting it into the companion object for `Fiber`, which honestly seems like a reasonable place for it to go. Would you be interested in fleshing that out into a pull request?

**Comment by scf37** [comment]
Is this still relevant given cats 2.0 is going to integrate `cats-par`?
Providing `Par` instance for `Concurrent` seems to be more straightforward.

**Comment by djspiewak** [comment]
I haven't been following exactly what's going on with cats-par, can you bring me up to speed? What would a `Par[Concurrent]` instance look like?

**Comment by scf37** [comment]
You probably know 2.0 plans better than me :-)

**Comment by djspiewak** [comment]
:-) This all sounds like a @ChristopherDavenport question. I legit don't know the answer.

**Comment by SystemFw** [comment]
The main question I have about this (and maybe it's a moot one), it's about implicit prioritisation.
We'd have  a `Concurrent[F] => Par[F]` coming from cats-effect, is it going to create any problems with instances coming from other places? (e.g. cats or monix)

**Comment by SystemFw** [comment]
@djspiewak re: `Par` and `Parallel`, `Par` is just a version of `Parallel` which encodes the applicative newtype as a type member instead of a type param (since the way it's used in Scala it's basically a unidirectional functional dependency, whereas haskell uses it in both directions).
The two type params in Parallel confuse a lot of people, since they try `Parallel[IO, IO]` instead of `Parallel[IO, IO.Par]` (and even more so in tagless final, where you need `F[_]` and `G[_]`), so I think the plan is simply to make `Parallel` in cats also move the `G[_]` into a type member).

In both cases, the instance should just encode `parMap2` with `start`, which sounds doable, bar the prioritisation question above.

**Comment by LukaJCB** [comment]
Btw some very early discussion on this (pre-`Concurrent`) can be found here: https://github.com/functional-streams-for-scala/fs2/issues/969
