### ISSUE TITLE
Reconsider Throwable addSuppressed usage

### ISSUE THREAD

**Issue by dwijnand** [typelevel/cats-effect#452]
See https://github.com/typelevel/cats-effect/pull/449 for an initial proposal and the exchange of thoughts and ideas around it.

**Comment by alexandru** [comment]
So inspired by the feedback we got on #449, the problem is basically `bracket` and for `bracket` specifically my current proposal is this:

1. if `use` throws, but `release` completes normally, then signal the error thrown in `use`
2. if `use` completes normally and `release` throws, then signal the error thrown in `release`
3. if both throw ... signal the error in `use` and log the error from `release`

Note that this goes for `guarantee` as well, since it's not directly based on `bracket`, having an optimized implementation.
