### ISSUE TITLE
Ongoing issues with simultaneous suite runs

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#49]
@alexandru it looks like we're having some issues with test suites running concurrently.  An example error:

```
[info] cats.effect.internals.OnceOnlyTests *** ABORTED ***
[info]   java.util.ConcurrentModificationException: Two threads have apparently attempted to run a suite at the same time. This has resulted in both threads attempting to concurrently change the current Informer. Suite class name: cats.effect.internals.OnceOnlyTests
[info]   at org.scalatest.AsyncSuperEngine$$anonfun$runImpl$1.apply(AsyncEngine.scala:626)
[info]   at org.scalatest.AsyncSuperEngine$$anonfun$runImpl$1.apply(AsyncEngine.scala:623)
[info]   at org.scalatest.CompositeStatus.whenCompleted(Status.scala:886)
[info]   at org.scalatest.AsyncSuperEngine.runImpl(AsyncEngine.scala:623)
[info]   at org.scalatest.AsyncFunSuiteLike$class.run(AsyncFunSuiteLike.scala:216)
[info]   at org.scalatest.AsyncFunSuite.run(AsyncFunSuite.scala:2187)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
```

I think this is related to some of the execution context work you did; would you mind taking a look?

**Comment by alexandru** [comment]
OK, I'll take a look.


On Tue, May 9, 2017, at 03:04, Daniel Spiewak wrote:
> @alexandru[1] it looks like we're having some issues with test suites
> running concurrently.  An example error:


> [info] cats.effect.internals.OnceOnlyTests *** ABORTED *** [info]
> java.util.ConcurrentModificationException: Two threads have apparently
> attempted to run a suite at the same time. This has resulted in both
> threads attempting to concurrently change the current Informer. Suite
> class name: cats.effect.internals.OnceOnlyTests [info]   at org.scala-
> test.AsyncSuperEngine$$anonfun$runImpl$1.apply(AsyncEngine.scala:626)
> [info]   at org.scalatest.AsyncSuperEngine$$anonfun$runImpl$1.apply(A-
> syncEngine.scala:623) [info]   at
> org.scalatest.CompositeStatus.whenCompleted(Status.scala:886) [info]
> at org.scalatest.AsyncSuperEngine.runImpl(AsyncEngine.scala:623)
> [info]   at org.scalatest.AsyncFunSuiteLike$class.run(AsyncFunSuiteLi-
> ke.scala:216) [info]   at
> org.scalatest.AsyncFunSuite.run(AsyncFunSuite.scala:2187) [info]   at
> org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite-
> (Framework.scala:314) [info]   at org.scalatest.tools.Framework$Scala-
> TestTask.execute(Framework.scala:480) [info]   at
> sbt.TestRunner.runTest$1(TestFramework.scala:76) [info]   at
> sbt.TestRunner.run(TestFramework.scala:85)
>> I think this is related to some of the execution context work you did;
> would you mind taking a look?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/alexandru
  2. https://github.com/typelevel/cats-effect/issues/49

**Comment by djspiewak** [comment]
This still appears to be an issue, albeit more rarely.

**Comment by alexandru** [comment]
This is also related to ScalaTest. I don't understand why it needs a lock, what an `Informer` is and why it needs to be modified concurrently. I've never had such problems with my own Minitest.

**Comment by djspiewak** [comment]
@bvenners Help? Anything obvious we might be doing wrong?

**Comment by bvenners** [comment]
Can you point me to the class that had the execution context work?

**Comment by alexandru** [comment]
Hi @bvenners,

One of the tests that triggered this problem is this: https://github.com/typelevel/cats-effect/blob/master/core/shared/src/test/scala/cats/effect/internals/OnceOnlyTests.scala

Indeed, the execution context gets overridden to Scala's `global` in order to test actual asynchrony. AFAIK ScalaTest uses by default an execution context that is faking async execution by manually managing a queue of runnables, which is also what we did in [TestContext](https://github.com/typelevel/cats-effect/blob/master/laws/shared/src/main/scala/cats/effect/laws/util/TestContext.scala).

In some tests that's not adequate, sometimes working with the real thing (e.g. Scala's global) is desirable.

We don't necessarily have to work with Scala's global though, so if we can configure a custom execution context, that's fine, but it should work with actual threads or with `setTimeout` on top of Javascript.

**Comment by bvenners** [comment]
@alexandru sorry for the long delay in responding. The error indicates two tests in the exact same suite instance are trying to be run concurrently. The model is that only one runs at a time. If you want the tests to run in parallel, then mix in ParallelTestExecution. That will run each test in its own instance of the test class, and should prevent the ConcurrentModificationException. That said, you shouldn't see it regardless, because even if you use the global execution context, because in async style tests each test is registered to run after the future for the previous test completes (unless you mix in ParallelTestExecution).
