### ISSUE TITLE
Cancelling the memo'd result of `Concurrent.memoize`

### ISSUE THREAD

**Issue by zarthross** [typelevel/cats-effect#530]
It appears that if you attempt to run a memo'd effect after some other call has canceled it the second attempt hangs indefinitely.  I could not find any issue, or documentation about what is expected to happen in this case.

Reproduction:
```
val ef = Timer[IO].sleep(2.seconds) // Long running IO
val mEF = Concurrent.memoize(ef)
val memoed = mEF.unsafeRunSync  // Get out the memoized version
val fiber = memoed.start
fiber.flatMap(_.cancel).unsafeRunSync

memoed.unsafeRunSync //Hangs indefinitely
```

I'm not sure if this is a bug that needs fixing, or just a opportunity for documentation improvement.

The cause of this specific issue is the deferred never completes: https://github.com/typelevel/cats-effect/blob/706b40f8f87dcf7779fd5926267138b9f2b9ee2e/core/shared/src/main/scala/cats/effect/Concurrent.scala#L368

**Comment by SystemFw** [comment]
So, I actually already had this in my todo list, the problem is not so much how to change the code, but rather deciding what the desired semantics are.
I think there are three possibilities:

- it becomes non terminating like now.
- it becomes interrupted as well (not currently possible in cats-effect)
- it fails with something akin to an InterruptedException

**Comment by zarthross** [comment]
I don't know that non-terminating is really that good of an option.  With fibers it might be ok to say in the docs 'cancel or join, not both' but for something like memoize it'll be hard to know if some downstream user fibers it, and then cancels, and all you did was call it again. 

There might be a 4th option though... where the wrapped effect is simply retried?  Not sure if that's even possible currently though.  In whichever case, i think its important we update the scala doc to explain the situation so users know that non-terminating is a possibility and then they can choose the `Async.memoize` which doesn't have the same issue..

**Comment by SystemFw** [comment]
Well, `Async.memoize` does not have the same issue because it cannot be canceled at all, so it's got a different issue :)

I don't necessarily disagree that non-termination is bad, but arbitrary retries seem just as bad, especially when you have guaranteed that things should only happen once. When I have similar scenarios in my own code I just complete the equivalent `Deferred` with an Exception, so that the client side can decide what to do. Right now in cats-effect you don't have the full set of choices though, i.e. you can't say "if this happen I want to cancel myself", you can only fail or retry

**Comment by oleg-py** [comment]
I'd vouch for the following semantics:
- If returned `F[A]` is bound multiple times already, cancelling is noop.
- If returned `F[A]` is not bound in any more, it's cancelled retried when it's next bound.

> "if this happen I want to cancel myself"
That sounds awesome out of context. /offtopic

**Comment by SystemFw** [comment]
> If returned F[A] is bound multiple times already, cancelling is noop.

this sounds like a good idea, although probably convoluted to implement

> If returned F[A] is not bound in any more, it's cancelled retried when it's next bound.

I'm a bit more doubtful of this one. It makes sense at first but note that with this semantics `memoize` no longer guarantees that things are done exactly once

**Comment by oleg-py** [comment]
> I'm a bit more doubtful of this one. It makes sense at first but note that with this semantics memoize no longer guarantees that things are done exactly once

Yes. I see it's either this, or "make cancel useless", and we already have `Async.memoize(fa)` and `Concurrent.memoize(fa.uncancelable)` that make it useless. And if nontermination of memoized binds is not desirable, that's the only option left I can think of.

**Comment by SystemFw** [comment]
I think I've convinced myself that the semantics @oleg-py proposed are the best for this combinators.
Ideally I'd like to hear other's people's opinions before implementing that.

Any thoughts?

**Comment by SystemFw** [comment]
I've got  a working implementation of this, I'll try to simplify the code a bit and open a PR

**Comment by SystemFw** [comment]
I spoke too soon. I have a working implementation of "cancel if there are no other consumers waiting, don't do anything otherwise"  with respect to the first inner `fa` (which is the one actually running the computation).  However, ensuring that these semantics hold in all cases is tricky, especially in cases where the `fa` that needs to cancel the computation is not the one that started it. I'll keep exploring.

**Comment by zarthross** [comment]
:+1: Thank you everyone.
