### ISSUE TITLE
Resource.allocated is unsafe when the Bracket type is eagerly-evaluated

### ISSUE THREAD

**Issue by vladimir-lu** [typelevel/cats-effect#532]
The current implementation of `Resource.allocated` evaluates the release too soon when `F[_]` is eagerly evaluated. This is an issue as the only bound on `allocated` is `Bracket`. In my case, I can construct an instance of `Bracket` for `scala.concurrent.Future` and it passes all the laws. The issue is inside the interpreter of allocated, where the `release: F[Unit]` instead of `release: => F[Unit]`. Similarly, `Resource.apply` also evaluates the release too soon.

Not sure how valid this is in the context of this project (the fix would be to presumably add an extra call-by-name parameter) but maybe it is worth adding extra bounds to `Resource` so that this can't happen with lawful cases of `F`.

**Comment by SystemFw** [comment]
This is a general problem with Future, not with `Resource`. When abstracting over `F`, you _have_ to assume referential transparency. 
Imagine something as simple as:
```scala
def repeat3Times[F[_]: Monad, A](fa: F[A]) = {
   val p = fa
   p >> p >> p
}
```
I wouldn't want to have to put a `Sync` bound there, because that would prevent legitimate uses with e.g. `Option`, just in case someone breaks referential transparency by using Future with side-effecting code.
In fact, this problem is one of the strongest arguments in favour of `IO` vs `Future`.

I can see that the argument is slightly more nuanced for `Resource`, because ultimately it's going to get used with an `F` with is at least `Sync`, however it's good to not impose a `Sync` constraint unless absolutely necessary, since you lose quite a lot of parametricity with that.

**Comment by djspiewak** [comment]
I'm going to close this. @SystemFw's argument is really strong: we *have* to assume referential transparency. As a good rule of thumb, if you can see a difference between `def f: Future[A]` and `val f: Future[A]`, for the future that you're constructing, then it isn't referentially transparent. (and by "see a difference", I mean, "the result of your program changes) A `Future` instance which isn't referentially transparent isn't even a lawful `Monad`! (though the laws cannot check this, because the laws themselves are referentially transparent) Code which abstracts over `F[_]` is always going to make the assumption that things are lawful according to their classes.
