### ISSUE TITLE
IO.raiseError(e) <-> IO(throw e) is violated for fatal errors

### ISSUE THREAD

**Issue by oleg-py** [typelevel/cats-effect#549]
In the following snippet:

```scala
import cats.effect.IO
  
IO.raiseError(new OutOfMemoryError())
  .handleErrorWith(_ => IO(println("Recovered"))
  .unsafeRunSync()
```

"Recovered" would be printed. If you replace the first line with `IO(throw new OutOfMemoryError())`, it would not. However, they are required (by a law in `SyncLaws`) to be equivalent.

This has caused confusion for some folks using Monix Task, as it suffers from the same issue [(gitter)](https://gitter.im/monix/monix?at=5cf3d07b6f530d3b6123ebfe).

I think `raiseError` should check for fatal-ness and throw in case the error is fatal. Maybe it's also worth adding some fatal errors into cats-effect test suite, to ensure equivalence.

**Comment by SystemFw** [comment]
Note that the current behaviour does not conflict with the specification for `MonadError` in general, it just defines the relationship between `Sync` and `MonadError`. If `raiseError` threw, then `raiseError(e).handleErrorWith(_ => fa) == fa` would cease to hold I think.
I'm not dead set either way though.

**Comment by alexandru** [comment]
`new OutOfMemoryError` is different from `throw new OutOfMemoryError`. The former creates a simple value, the later blows up the stack.

> However, they are required (by a law in SyncLaws) to be equivalent.

That's not a good reason, since that law is meant for errors that are `NonFatal`.

What valid use-cases do people have for `IO.raiseError(new OutOfMemoryError())` anyway?

**Comment by SystemFw** [comment]
yeah I don't think there is a use case. It's a semi common question when people want to test out the behaviour with fatal errors and they do it with `raiseError` instead `IO(throw)`

**Comment by kryptt** [comment]
I think the reasoning for the issue is about cementing the differences between fatal and non-fatal errors. For example, a solution could be just mentioning the divergence in behavior in the scaladoc for raiseError, or possibly write down elsewhere in the doc that moving fatal errors through IO could lead to undefined behavior; i.e. warn people not to use IO.raiseError(new SomeFatalError()) if its not desirable to work on adding tests / defining behavior under those situations..

**Comment by alexandru** [comment]
I'd love to solve this via types, the JVM has traditionally used [Error](https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html) to signal fatal errors and [Exception](https://docs.oracle.com/javase/7/docs/api/java/lang/Exception.html) for errors that the user is free to catch.

We have been using Scala's [NonFatal](https://www.scala-lang.org/api/2.9.3/scala/util/control/NonFatal$.html) which has this test:

```scala
case _: VirtualMachineError | _: ThreadDeath | _: InterruptedException | _: LinkageError | _: ControlThrowable => false
```

We do this because:

1. not that many `Error` types are fatal, surely an `AssertionError` can be caught without the world ending, even if it signals a bug
2. we have `InterruptedException`, which is an odd one ... if you catch it and you don't re-throw it immediately, then this needs to be deliberate

One possibility is that we could switch the implementation to catch `Exception` instead of `Throwable` / `Error`. And we could deal with `InterruptedException` separately, which we should probably do in some fashion anyway.

**Comment by djspiewak** [comment]
I don't think there's any way to resolve this with types, since things are so overlapping. My first instinct is to just say that "when you're throwing fatal errors, all bets are off". I don't think any of the laws reasonably hold at that point, for the same reason that none of the laws reasonably hold if you do `IO(System.exit(0))`. You're just falling into the black hole and leaving our universe.

I don't think that changing the behavior of `raiseError` in `MonadError` is the answer, either, since `MonadError` is at the very least generic in its error type. It would be pretty logistically difficult to make that work without witchcraft, and even then I'm not sure it would buy us anything.

I'm pretty comfortable saying that `IO(throw e) <-> IO.raiseError(e)` *only* holds if `e` is non-fatal.
