### ISSUE TITLE
.allocated.continual can be cancelled without running finalizers

### ISSUE THREAD

**Issue by nigredo-tori** [typelevel/cats-effect#579]
Test case:
```scala
def say(s: String): IO[Unit] = IO { println(s) }

val slowRes = Resource.make(
  (timer.sleep(1.second) *> say("Acquired")).uncancelable
)(_ => say("Released"))

slowRes.allocated.continual {
  case Right((_, release)) => release
  case Left(_) => say("Failed")
}.timeoutTo(500.millis, IO.unit)
```
`.allocated` doc:

> If the outer F fails or is interrupted, allocated guarantees that **the finalizers will be called**.

`.continual` doc:

> fa is interruptible, but if it completes execution, **the effects of f are guaranteed to execute**. 

Yet the finalizers are not called here.

I've checked this on master and on 2.0.0-M4.

**Comment by nigredo-tori** [comment]
Also weird:
```scala
(say("Foo") *> timer.sleep(1.second) *> say("Bar"))
  .uncancelable
  .guarantee(say(s"Baz")).void
  .timeoutTo(500.millis, IO.unit)
```
The example above prints:
```
Foo
Baz
Bar
```
in this order.

**Comment by nigredo-tori** [comment]
It seems I misunderstood `.uncancelable`. `fa.uncancelable` means that `fa` won't be cancelled, but the resulting action might (that is, with `.guaranteeCase(f)` on it `f` might receive an `ExitCase.Cancelled`). More generally, the action can be considered cancelled (as observed by `guaranteeCase`) even if did complete successfully:
```scala
// Some long "opaque" action
IO {
    // Example blocking code
  for {_ <- 1 to 100} {
    println("Waiting...")
  }
  println("Foo")
}.guaranteeCase { ec => say(ec.toString) }
  .timeoutTo(1.millis, IO.unit)
```
The above example prints `Cancelled`, and only then `Foo` - again, the order is surprising here.

This is getting confusing WRT releasing resources - seems like the only thing I can really trust with that is `bracketCase`... Off the top of my head I can't see a good way to add a timeout/race to resource acquisition (which is why I dove in this rabbithole in the first place). Is it even possible?

**Comment by oleg-py** [comment]
@nigredo-tori `fa.uncancelable` means `fa` will never react on cancel signal, continuing until finishing. But anything before or after it is fair game. The fact that `continual` doesn't work properly here is a bug, however.

**Comment by SystemFw** [comment]
@oleg-py  @nigredo-tori Just seen this somehow. 
`continual` is a red herring, here is what's happening.
First of all, the problem can be reproduced with just `allocated`.
```scala
def ex = {
    def say(s: String): IO[Unit] = IO { println(s) }
    def res = Resource.make {
      IO.sleep(1.second) *> say("Acquired")
    } { _ => say("Released") }

    res.allocated.start.flatMap { fib =>
      IO.sleep(500.millis) >> fib.cancel
    }
  }.unsafeRunSync

scala> ex
Acquired
```

If you do substitute the definition of `allocated` and go to the relevant case, you can get a minimal repro that doesn't involve `Resource`
```scala
def ex = {
    def say(s: String): IO[Unit] = IO { println(s) }
    def res = Resource.make {
      IO.sleep(1.second) *> say("Acquired")
    } { _ => say("Released") }


    res.allocated.start.flatMap { fib =>
      IO.sleep(500.millis) >> fib.cancel
    }
  }.unsafeRunSync


  def ex0 = {
    def say(s: String): IO[Unit] = IO { println(s) }
   
    (IO.sleep(1.second) *> say("Acquired"))
      .bracketCase(_ => IO.unit) {
        case (_, ExitCase.Completed) =>
         IO.unit
        case _ =>
          say("released")
      }
      .start.flatMap { fib => IO.sleep(500.millis) >> fib.cancel }
  }.unsafeRunSync

scala> ex0
Acquired
```
and that's the crux of the issue: `bracketCase` means that the action is `uncancelable` (which is the correct translation for `allocated`, `Resource` can be canceled between `flatMap`s, but the individual `Allocated` nodes should be uncancelable). Because the action is `uncancelable`, the cancelation signal is ignored and the `bracketCase` hits the `Completed` case, which doesn't trigger the release (which again is the correct semantics for `allocated`).

To make it release resources, one needs to make sure that `allocated` is actually cancelled, which can happen is there is at least one `flatMap`. In other words, this works
```scala
def ex = {
    def say(s: String): IO[Unit] = IO { println(s) }
    def res = Resource.make {
      IO.sleep(1.second) *> say("Acquired")
    } { _ => say("Released") }


    res.allocated.start.flatMap { fib =>
      IO.sleep(500.millis) >> fib.cancel
    }
  }.unsafeRunSync


  def ex0 = {
    def say(s: String): IO[Unit] = IO { println(s) }
   
    (IO.sleep(1.second) *> say("Acquired"))
      .bracketCase(_ => IO.unit) {
        case (_, ExitCase.Completed) =>
         IO.unit
        case _ =>
          say("released")
      }
      .start.flatMap { fib => IO.sleep(500.millis) >> fib.cancel }
  }.unsafeRunSync


  def ex1 = {
    def say(s: String): IO[Unit] = IO { println(s) }
    def res = Resource.make {
      IO.sleep(1.second) *> say("Acquired")
    } { _ => say("Released") } << ().pure[Resource[IO, ?]]


    res.allocated.start.flatMap { fib =>
      IO.sleep(500.millis) >> fib.cancel
    }
  }.unsafeRunSync

scala> ex1
Acquired
Released
```

------------------

Now, the interesting question is what the right behaviour should be, which can be distilled to the following fundamental question:

> if an `uncancelable` `IO` receives the cancelation signal, should it terminate with `Completed` or `Canceled`?

I think the problem here is that there is some ambiguity with regards to what `Canceled` means:
- `Canceled` means the `IO` received the cancelation signal
- `Canceled` means the `IO` _respected_ the cancelation signal


@alexandru @djspiewak particularly interested in your thoughts here

**Comment by SystemFw** [comment]
Ok, look at this:

```scala
def say(s: String): IO[Unit] = IO { println(s) }
def ex2 = 
  IO.sleep(1.second)
    .bracketCase(_ => IO.unit) {(_, ec)  => say(ec.toString)}
    .start.flatMap { fib => IO.sleep(500.millis) >> fib.cancel }
    .unsafeRunSync

def ex3 = 
  IO.sleep(1.second)
    .uncancelable
    .guaranteeCase(ec  => say(ec.toString))
    .start.flatMap { fib => IO.sleep(500.millis) >> fib.cancel }
    .unsafeRunSync

scala> ex2
Completed

scala> ex3
Canceled
```

**Comment by SystemFw** [comment]
Ok, the `ex3` above makes more sense when you expand it (even though `IO` overrides things like `guaranteeCase`, both the expanded and non expanded version show the same result)

```scala
def ex5 =
    IO.unit.bracketCase { _ =>
      IO.sleep(1.second)
        .bracketCase(x => IO.pure(x)){case (_,ec) => say(s"inner ${ec.toString}")}
    }{case (_,ec)  => say(s"outer ${ec.toString}")}
      .start.flatMap { fib => IO.sleep(500.millis) >> fib.cancel }
      .unsafeRunSync

scala> ex5
inner Completed
outer Canceled
```
Even though this behaviour makes sense to me in isolation, the interaction with `allocated` above is concerning.
A quick fix would be to change `allocated` to insert a `flatMap` like above, but I'd like to get to the bottom of the semantics for `ExitCase` here, to see if we need to change something

**Comment by djspiewak** [comment]
@SystemFw Yeah the expanded example definitely makes sense.

So regarding the meaning of `Canceled`, I almost think it *has* to be that the `IO` *received* the signal. We can't really say definitively whether or not an action *respected* the signal. Imagine something defined with `cancelableF` where the cancel token is fired but, for whatever reason, the effect couldn't actually unschedule whatever was happening (perhaps because there was a race and the scheduler had just picked up the action). Or even something simpler like `IO(Thread.sleep(2000)).start.flatMap(_.cancel)`.

This does create an unfortunate race ambiguity though if you do something like `IO.pure(42).start.flatMap(_.cancel)`. If we cancel something that has already completed, is it `Canceled` or is it `Completed`? This probably needs to be driven by the semantics of `join`, but those are already murky at best.
