### ISSUE TITLE
Why I can't get underlying `ExecutionContext` from `ContextShift[IO]`?

### ISSUE THREAD

**Issue by taeguk** [typelevel/cats-effect#619]
I can construct `ContextShift[IO]` from `ExecutionContext`.
But why there is no way to get underlying `ExecutionContext` from `ContextShift[IO]`?
(I found that underlying execution context is declared as `private`.)

**Comment by djspiewak** [comment]
Because not all implementations actually have an `ExecutionContext` inside the `ContextShift`. Though, with that said, all implementations do have access to an EC at all times given an implicit `ContextShift`, so we could probably add that functionality and it would be extremely useful.

Cats Effect 3 will have a much more elegant solution to this problem.

**Comment by neko-kai** [comment]
@djspiewak 
> Cats Effect 3 will have a much more elegant solution to this problem.

Would you mind sharing?

**Comment by djspiewak** [comment]
@neko-kai What I'm currently thinking is a pair of functions on the typeclasses that imply a reader:

```scala
def executionContext: F[ExecutionContext]
def evalOn[A](fa: F[A], ec: ExecutionContext): F[A]
```

Such that `evalOn(executionContext, ec) <-> pure(ec)`.

That's just the current thought. Obviously `IO` will have to be adjusted considerably to take advantage of this, and it will constrain all downstream implementations to thread an `ExecutionContext` through their run loop, but as far as I'm concerned, that's the correct approach.

**Comment by alexandru** [comment]
Designing IO to have an injected EC in its run-loop is the right approach and what Monix has always done.

Designing the type classes to assume that EC isn't necessarily the right approach.

One of these days I'll resurect all IO implementations we've had since the very first release and all types classes we introduce have to make sense for all of them 🙂

**Comment by alexandru** [comment]
So I'm not 100% sure that we should expose an ExecutionContext in the API.

The one area where it definitely helps is in wrapping Future-driven APIs. But keep in mind it's FFI. And low level.

I would do this btw, a version of defer / suspend that we've had:

```scala
def deferAction[A](f: ExecutionContext => F[A]): F[A]
```

But for the reasons mentioned above, I'm not super sure I want such a thing in our type classes.

**Comment by djspiewak** [comment]
> So I'm not 100% sure that we should expose an ExecutionContext in the API.

Why exactly?

> I would do this btw, a version of defer / suspend that we've had:

I mean, `executionContext` is nothing more than `deferAction(pure(_))`, and `deferAction` is simply `flatMap(executionContext)`, so I'm not sure I see the difference exactly. `executionContext` is just a cleaner formulation IMO, since it's less tangled with other concepts.

> But for the reasons mentioned above, I'm not super sure I want such a thing in our type classes.

It's more about being able to support interop with APIs which directly take `ExecutionContext`. `Future` is one example, but there are certainly others. I honestly don't think we can avoid it. If we don't have something like this, then we force API warts like some of what http4s has had to go through to wrap Blaze.

**Comment by djspiewak** [comment]
> Designing the type classes to assume that EC isn't necessarily the right approach.

Oh, to this point… The problem is that if we *don't* design the typeclasses in this way, then we cannot provide guarantees surrounding context affinity following `async`, which is something that I very *very* much want to do. Yes, this design definitely constrains implementations quite considerably in that it *forces* them to inject an EC into the run loop (or use an alternative approach, like what @julien-truffaut experimented with in the gitter channel), but those constraints are worth it given that we can get sane laws around context.

**Comment by alexandru** [comment]
> then we cannot provide guarantees surrounding context affinity following async, which is something that I very very much want to do

For one, I don't really understand what's the problem in not doing that 🙂

Also who's to say that an injected `ExecutionContext` is needed. I can think of:

1. JavaScript doesn't really need execution contexts — the only thing you might want is the use of a trampoline, but that's rare and most people just work with `setTimeout`
2. Usage of a single, global `ExecutionContext`, because why not? The liberal use of thread-pools only happens on top of the JVM and for example on top of .NET, a close cousin of the JVM that still does 1:1 multi-threading, they use a single thread-pool (for better or worse)

Having the ability to switch to a different (global) execution context is an implementation detail.

**Comment by alexandru** [comment]
Also the laws test for equivalence (can the left hand side be substituted for the right hand side?), so I think it's an irrelevant implementation detail also because you can't really specify that by law (in a way that's not essentially a no-op)  without some really nasty hacks involved.

**Comment by alexandru** [comment]
Btw, I don't completely disagree with exposing that `F[ExecutionContext]`, because it certainly makes interop (with `Future` APIs) easier, just challenging this point a little.

Otherwise if you feel it is absolutely needed, I think we could expose `F[ExecutionContext]` in `ContextShift[F]`, the problem being that it breaks binary compat, so we can't do it too soon.
