### ISSUE TITLE
Inconsistent behavior with shift.productR

### ISSUE THREAD

**Issue by scf37** [typelevel/cats-effect#745]
`val cs = IO.contextShift(ExecutionContext.global)`

// throws exception
`(IO(throw new OutOfMemoryError()) >> cs.shift >> IO()).unsafeRunSync()`

// hangs forever
`(cs.shift.productR(IO(throw new OutOfMemoryError())) >> IO()).unsafeRunSync()`

cats-effect 2.0.0
cats 2.0.0

**Comment by djspiewak** [comment]
The problem here is actually `ExecutionContext.global`. It catches the OOM and swallows it. Pretty sure you can get this even without `productR`:

```scala
(cs.shift >> IO(throw new OutOfMemoryError())).unsafeRunSync()
```

I'd be willing to bet that hangs with `global`. You won't have this problem with the `IOApp` pool.

The consistent philosophy of Cats Effect is that fatal errors are fatal and shouldn't be handled. I've seen horrible, horrible, horrible things happen when you try to catch fatal errors (OOM especially, but I've also seen it with SOE and the various link errors).

**Comment by scf37** [comment]
I thought it is a guarantee that in case of OOM `unsafeRunSync()` throws.

Therefore, `ExecutionContext` with early termination on `Error`  is the only safe choice? Safe - ensuring that application terminates on Error.

**Comment by gurinderu** [comment]
@djspiewak maybe it is time to make a custom cats.ExecutionContext with the same guarantees as in IOApp and replace all usages of scala.concurrent. ExecutionContext?

**Comment by djspiewak** [comment]
> maybe it is time to make a custom cats.ExecutionContext with the same guarantees as in IOApp and replace all usages of scala.concurrent. ExecutionContext?

I've thought about it! One problem that you run into if you do that though is that people pretty much need to be as disciplined with such a pool as people generally are within the CE ecosystem. Cats Effect, by its very design and the design of the frameworks in its ecosystem, pushes you pretty strongly towards careful pool usage. This means that the primary compute pool can be more aggressively tuned. If people *weren't* being careful but they still used the pool in `IOApp`, then they would see inevitable livelocks caused by thread starvation, and that's no one's idea of a good time.

An alternative is trying to open up the utility which enriches an existing `ExecutionContext` with "fatal errors are fatal" semantics. That's in `PoolUtils` right now. Wouldn't fix global, but it would at least give people something of a middle ground.

**Comment by gurinderu** [comment]
> This means that the primary compute pool can be more aggressively tuned.

But we can introduce our type with a delegation to the underlying pool.  Something like this cats.effect.ExecutionContext.fromScalaEC or cats.effect.ExecutionContext.fromJavaExecutor. It gets you a type guarantee that nobody can't use unsafe context and it is still flexible for tuning.
