### ISSUE TITLE
Consider exposing IOApp's ExecutionContext as `protected`

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#748]

**Comment by Daenyth** [comment]
Currently the workaround for users who want to share one EC between `Future`-ish scala and their `ContextShift` is this

- use `IOApp.WithContext`
- copy the logic from `PoolUtils` (related: #755) so that your EC is set up the same way
- In your `IOApp.WithContext`, use the inherited `executionContext` as needed (as your `implicit ec`), in addition to using the `ContextShift` that wraps it
