### ISSUE TITLE
Proposal: expose PoolUtils as part of the API

### ISSUE THREAD

**Issue by lorandszakacs** [typelevel/cats-effect#755]
Hello folks,

I would argue that it's a good idea to expose `PoolUtils` as part of the API. This would allow users of the CE runtime to, at least:
- easily customize the names of the default thread pool without having to go down and dirty into the Java stuff (for me at least, writing any Java code is already painful 😰), and without duplicating the pool creation code of the existing [main IOApp pool](https://github.com/typelevel/cats-effect/blob/master/core/jvm/src/main/scala/cats/effect/internals/PoolUtils.scala#L28)
- easily create other "common" types of pools (e.g. cached, single thread)

I have already rolled my own version of this stuff in `pureharm-effects-cats`, you can have a look:
[https://github.com/busymachines/pureharm/blob/master/effects-cats/src/main/scala/busymachines/pureharm/effects/pools/Pools.scala](https://github.com/busymachines/pureharm/blob/master/effects-cats/src/main/scala/busymachines/pureharm/effects/pools/Pools.scala)

Now, not sure if this adds a lot of complication for the JS support or not. I have never maintained a scala-js library before.

**Comment by kubukoz** [comment]
Either this, or providing the default ExecutionContext used for the ContextShift instance in IOApp would be of great benefit.

**Comment by jgogstad** [comment]
This would be very useful on platforms with only once core available; it's particularly relevant for JVMs running on data processing pipelines where the number of cores available is typically lower than usual.

Using `global` when there's only one core available frequently leads to deadlocks since [global doesn't have a lower bound](https://github.com/scala/scala/blob/706ef1b291134a5e5bce2275df2c222261f73451/src/library/scala/concurrent/impl/ExecutionContextImpl.scala#L91); submitting tasks to an `ExecutorService` would be unsafe for example. Right now we need to explicitly allocate another lower bounded thread pool for CPU tasks.

Another argument is that it will be easier to work with APIs that takes arguments of type `ExecutionContext` for CPU bounded workloads, for instance http4's `BlazeClientBuilder`.

**Comment by alexandru** [comment]
I don't agree with exposing `PoolUtil`, that code is too low level and once something becomes part of the API in Cats-Effect, it's a pretty permanent change.

That code is a pretty standard way to create a thread pool on the JVM. It's a JVM-wide concern that's not related much to Cats-Effect's core.  And in `IOApp` the `ContextShift` can be overridden precisely because the default isn't good for everyone.

@kubukoz 

> Either this, or providing the default ExecutionContext used for the ContextShift instance in IOApp would be of great benefit.

Our mistake there was to not expose `ExecutionContext` in `ContextShift`, which is where it should be. Not sure if there's anything we could do now, until CE 3.
