### ISSUE TITLE
Clock[OptionT[F, *]] leads to implicit derivation issues

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/cats-effect#784]
Currently attempting to consume this middleware in http4s, [Caching.`no-store`](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/middleware/Caching.scala#L24) and the below is what we derive when using `HttpRoutes`.

Would be nice to not need to explicitly pick a derivation approach.

```
ambiguous implicit values:
 both method deriveOptionT in trait LowPriorityImplicits of type [F[_]](implicit F: cats.Functor[F], implicit clock: cats.effect.Clock[F])cats.effect.Clock[[β$2$]cats.data.OptionT[F,β$2$]]
 and method extractFromTimer in object Clock of type [F[_]](implicit timer: cats.effect.Timer[F])cats.effect.Clock[F]
 match expected type cats.effect.Clock[[A]cats.data.OptionT[F,A]]
```

**Comment by djspiewak** [comment]
Oh… because they're actually unrelated types. That's a very annoying problem.

**Comment by djspiewak** [comment]
Having passively thought about this for a while… I think the only real solution, since these are *separate* types, is to make some part of this explicit. And I think the correct one to make explicit is `extractFromTimer`, unfortunately. It's relatively easy to still get a `Clock` from a `Timer` when that function is explicit, but in the alternative universe (where we remove or make-explicit `deriveOptionT`), manually performing inductive derivations is immensely annoying.

I sound like a broken record, but… ce3 avoids these problems by unifying things together into a `Temporal` typeclass, which is a proper part of the hierarchy. IMO ce2 should have done something similar, or even make `Timer` inherit from `Clock`. Any time you have an *implicit* such as `extractFromTimer` and you're not dealing with third-party types (everything here is first-party), then subtyping is usually the better encoding. We can't do that now though without breaking compatibility.

So my proposal: remove the `implicit` modifier from `extractFromTimer` and break everyone's source. :-( Bincompat is preserved, but source compat is lost. This would be a 2.2.0 or 2.3.0 change.

**Comment by joroKr21** [comment]
That's on Scala 2.13.1 only right?

**Comment by alexandru** [comment]
@djspiewak 
> I sound like a broken record, but… ce3 avoids these problems by unifying things together into a `Temporal` typeclass, which is a proper part of the hierarchy.

This is probably the better design choice, however note that this restricts implementations to ones that inject their `ExecutionContext` and `Scheduler` via their run-loop, like what Monix is doing, versus ones that require them as parameters only on operations that need it, like the current `IO`.

Which is the better design choice is debatable. I personally like injecting that via the run-loop, b/c operations that require it are pervasive. In Monix due to fairness guarantees, the ability to yield execution to an underlying run-loop made this design choice easy. In `IO` you designed the run-loop without such constraints and it's what made us use `IO` for synchronous stuff and later have `SyncIO` directly based on it, instead of having a `Coeval` with an entirely separate implementation like in Monix.

As the `Temporal` in CE 3 is designed, the current `IO` cannot implement an instance for it, without that instance requiring some sort of implicit `Scheduler` / `ExecutionContext`.

**Comment by alexandru** [comment]
... I've hit Send before finishing. 

So `Temporal` from CE 3 is probably the right design choice, especially after later changes in `IO` that require an execution context for `start`, which makes it require an `ExecutionContext` for a `Concurrent[IO]` instance anyway. But there's a compromise there we should be aware of.

**Comment by SystemFw** [comment]
I think not injecting the EC in the runloop for `IO` proved a mistake (although all the steps that led there made sense individually at the time). Basically right now if you want to use concrete `IO`, you don't have an implicit free experience, which I think it's a bummer for teams that are starting out.

> the current IO cannot implement an instance for it, without that instance requiring some sort of implicit Scheduler / ExecutionContext.

Note that this isn't really any worse than the current situation for `Concurrent[ce2.IO]` (which I don't like in either case, but it does work)

**Comment by alexandru** [comment]
> Note that this isn't really any worse than the current situation for Concurrent[ce2.IO] (which I don't like in either case, but it does work)

Yes, I followed up in another message, we eventually ended up with the current `Concurrent[ce2.IO]` so judging in retrospective, we haven't gained that much. And I'm now in support of `Temporal` from CE 3.
