### ISSUE TITLE
IOApp yields console errors when executed in browser

### ISSUE THREAD

**Issue by Taig** [typelevel/cats-effect#838]
Probably related to / introduced by #809 

**build.sbt**
```scala
enablePlugins(ScalaJSPlugin)

scalaVersion := "2.13.1"

libraryDependencies += "org.typelevel" %%% "cats-effect" % "2.1.3"

scalaJSUseMainModuleInitializer := true
```

**App.scala**
```scala
import cats.effect.{ExitCode, IO, IOApp}

object App extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = IO(ExitCode.Success)
}
```

**index.html**
```html
<!DOCTYPE html>
<html lang="en">
<body>
<script src="target/scala-2.13/ce-test-fastopt.js"></script>
</body>
</html>
```

**Console output**
`scala.scalajs.js.JavaScriptException: ReferenceError: process is not defined`

![Bildschirmfoto 2020-04-18 um 12 24 29](https://user-images.githubusercontent.com/567857/79635198-d9951300-816f-11ea-9369-d73eb2018357.png)

**Comment by rossabaker** [comment]
Yes, this almost certainly caused by [this](https://github.com/typelevel/cats-effect/pull/812#discussion_r389333325).

I am very ignorant of scala.js (and indeed, JS itself!).  What is the use case for `IOApp` inside the browser?  And is there any sense of exiting?  Any way to communicate an exit code?

**Comment by Taig** [comment]
I don't know how/if the exit code is handled in the JS environment. The use case for me was simply the habit of wiring my app together in `IOApp`, not having to worry about `ContextShift` and `Timer` instances. I don't mind rolling my own `main` method for now and would offer to take a stab at this issue in the coming days.

**Comment by rossabaker** [comment]
I think we could capture the `JavaScriptException` like we used to, but the question is what to do about it, since we can no longer exit.  Probably also worth thinking about how it operates in scala.js's other supported environments: there are more than node and the browser, though I don't know how prevalent they are.
