### ISSUE TITLE
Improve performance of IO async, start, and race

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#921]
The concurrency operations on `IOFiber` are relatively slow, particularly compared to master. *Some* of that is a consequence of the fact that `async` in CE3 provides considerably stronger sequencing guarantees than `async` on master, but I still think we can be quite a bit faster. The performance difference is an order of magnitude under some circumstances, which is quite meaningful.

**Comment by RaasAhsan** [comment]
I think a considerable portion of the slowdown comes from the internal shifting behavior of CE3 IO. Some ideas here that would certainly speed up `start` and `race`:
1. Add a shifting flag that is opt-out option. `start` and `race` would opt-out, since we're guaranteed to be on the default `ExecutonContext` as long as we don't expose this flag in the public API
2. Stack safety is now a concern. We can port the trampolining `ExecutionContext` implementation from Cats Effect 2, in conjunction with the opt-out flag.
3. Another idea to address stack safety is to keep track of a async depth counter. If we re-enter the run-loop from an async boundary and the depth counter exceeds some threshold, then do a shift regardless of what the shift flag is.

We can probably use this for `join` and `cancel` as well. Thoughts?

**Comment by RaasAhsan** [comment]
I keep on mixing up Cats Effect 2 and 3 semantics. Cats Effect 2 implemented both `start` and `racePair` as `Async`, but CE3 only implements the latter as such. Plus, for `join` and `cancel`, we need to explicitly shift threads anyway since we might have several.

A ton of combinators were derived from `Async` in CE2, but I don't think that's the case any longer for CE3. The only compelling case here is `racePair`, but it may not be worth all the extra trampolining machinery to make it fast.
