### ISSUE TITLE
SemigroupK[IO]

### ISSUE THREAD

**Issue by fommil** [typelevel/cats-effect#94]
I was writing a DSL that required boolean OR logic with early exit and used `SemigroupK` as a way to achieve this, however without an instance I was not able to use `IO`. It would be good to provide one.

**Comment by fommil** [comment]
```scala
  implicit val IOPlus: SemigroupK[IO] = new SemigroupK[IO] {
    def combineK[A](x: IO[A], y: IO[A]): IO[A] = x.handleErrorWith(_ => y)
  }
```

**Comment by fommil** [comment]
There was a horrid suggestion on the gitter channel to provide an `Alternative` by returning a failed `IO`. I guess that works.

**Comment by alexandru** [comment]
For Strings the concatenation operation makes the canonical `Semigroup` / `Monoid`, same for Lists.

Not having a problem with adding a `SemigroupK[IO]`, however given that we try to be coherent in our type-class definitions, I'm not sure what makes `x.handleErrorWith(_ => y)` canonical.  It's not very obvious to me, especially the `IO[A]` values aren't both evaluated.

A more obvious definition for me would be something that evaluates both:

```scala
x.flatMap(_ => y)

x.flatMap(x => y.map(_ => x))
```

But maybe this isn't obvious enough either. More obvious is `Semigroup[IO[A]]` for any `A : Semigroup[A]`, which is already defined.

So I'm not sure how to help. Somebody more knowledgeable with this stuff needs to comment.

**Comment by alexandru** [comment]
Also, I'm not sure if my expectation for evaluating both helps, since you want "*OR logic*", so I'm assuming that evaluating both is precisely what you don't want?

I guess that what I'm asking is why would anybody expect `x.handleErrorWith(_ => y)` to be the implementation of a `SemigroupK[IO]`?

Is there some theory or precedent in other libraries?

**Comment by fommil** [comment]
Plus (or as cats have renamed it, SemigroupK) has "pick the first winner, ignore errors" semantics. Although it is not expressed in its laws.

**Comment by alexandru** [comment]
Semigroup comes from category theory, I'm only familiar with the laws I learned in my 12th grade — kids in Romania learn about semigroups and monoids in high-school, guess we got lucky 😀

Those semantics are interesting. If that's the case, guess it makes sense, but are there examples of such instances in other libraries? Cats, Scalaz, Haskell, PureScript? If this can be expected given prior work, then we could have a `SemigroupK[IO]` instance.

I know that issues aren't for tutoring, but I saw this issue lingering since a week ago, so I'm asking in absence of somebody else more knowledgeable confirming this.

**Comment by mpilquist** [comment]
> Plus (or as cats have renamed it, SemigroupK) has "pick the first winner, ignore errors" semantics. Although it is not expressed in its laws.

This is a property of certain lawful instances but not of the type class itself. The type class only defines  a universally quantified associative combine operation. For example, consider `MonoidK[List]`.

**Comment by mpilquist** [comment]
Here's another example which is more fundamental:

```scala
implicit def semigroupKConst[A](implicit A: Semigroup[A]): SemigroupK[Const[A,?]] = new SemigroupK[Const[A,?]] {
    def combineK[B](x: Const[A,B], y: Const[A,B]): Const[A,B] = Const(A.combine(x.getConst, y.getConst))
  }
```

**Comment by fommil** [comment]
well, yes, I guess it's more like "pick the first winner, ignoring failures, unless there are no winners. then we all lose"

**Comment by mpilquist** [comment]
:) I feel like the expectation mismatch leads to https://github.com/quchen/articles/blob/master/monad_fail.md.

Anyway, I'm :+1: on a `SemigroupK[IO]` as proposed.
